// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

package helloworld

import "github.com/iotaledger/wasplib/packages/vm/wasmlib"

const (
	ScName = "helloworld"
	ScDescription = "The ubiquitous hello world demo"
	HScName = wasmlib.ScHname(0x0683223c)

	ResultHelloWorld = wasmlib.Key("helloWorld")

	FuncHelloWorld = "helloWorld"
	ViewGetHelloWorld = "getHelloWorld"

	HFuncHelloWorld = wasmlib.ScHname(0x9d042e65)
	HViewGetHelloWorld = wasmlib.ScHname(0x210439ce)
)
