// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package coreeventlog

import "github.com/iotaledger/wasplib/packages/vm/wasmlib"

type GetNumRecordsCall struct {
	Func    *wasmlib.ScView
	Params  MutableGetNumRecordsParams
	Results ImmutableGetNumRecordsResults
}

func NewGetNumRecordsCall(ctx wasmlib.ScViewCallContext) *GetNumRecordsCall {
	f := &GetNumRecordsCall{Func: wasmlib.NewScView(HScName, HViewGetNumRecords)}
	f.Func.SetPtrs(&f.Params.id, &f.Results.id)
	return f
}

type GetRecordsCall struct {
	Func    *wasmlib.ScView
	Params  MutableGetRecordsParams
	Results ImmutableGetRecordsResults
}

func NewGetRecordsCall(ctx wasmlib.ScViewCallContext) *GetRecordsCall {
	f := &GetRecordsCall{Func: wasmlib.NewScView(HScName, HViewGetRecords)}
	f.Func.SetPtrs(&f.Params.id, &f.Results.id)
	return f
}
