// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

use dummy::*;
use schema::*;
use wasmlib::*;

mod dummy;
mod schema;

#[no_mangle]
fn on_load() {
    let exports = ScExports::new();
    exports.add_call(FUNC_INIT, func_init_thunk);
}

//@formatter:off
pub struct FuncInitParams {
    pub fail_init_param: ScImmutableInt, // when present fail on purpose
}
//@formatter:on

fn func_init_thunk(ctx: &ScCallContext) {
    let p = ctx.params();
    let params = FuncInitParams {
        fail_init_param: p.get_int(PARAM_FAIL_INIT_PARAM),
    };
    func_init(ctx, &params);
}
