// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

package coreroot

import "github.com/iotaledger/wasplib/packages/vm/wasmlib"

type ClaimChainOwnershipCall struct {
	Func *wasmlib.ScFunc
}

func NewClaimChainOwnershipCall(ctx wasmlib.ScFuncContext) *ClaimChainOwnershipCall {
	return &ClaimChainOwnershipCall{Func: wasmlib.NewScFunc(HScName, HFuncClaimChainOwnership)}
}

type DelegateChainOwnershipCall struct {
	Func *wasmlib.ScFunc
	Params MutableDelegateChainOwnershipParams
}

func NewDelegateChainOwnershipCall(ctx wasmlib.ScFuncContext) *DelegateChainOwnershipCall {
	f := &DelegateChainOwnershipCall{Func: wasmlib.NewScFunc(HScName, HFuncDelegateChainOwnership)}
	f.Func.SetPtrs(&f.Params.id, nil)
	return f
}

type DeployContractCall struct {
	Func *wasmlib.ScFunc
	Params MutableDeployContractParams
}

func NewDeployContractCall(ctx wasmlib.ScFuncContext) *DeployContractCall {
	f := &DeployContractCall{Func: wasmlib.NewScFunc(HScName, HFuncDeployContract)}
	f.Func.SetPtrs(&f.Params.id, nil)
	return f
}

type GrantDeployPermissionCall struct {
	Func *wasmlib.ScFunc
	Params MutableGrantDeployPermissionParams
}

func NewGrantDeployPermissionCall(ctx wasmlib.ScFuncContext) *GrantDeployPermissionCall {
	f := &GrantDeployPermissionCall{Func: wasmlib.NewScFunc(HScName, HFuncGrantDeployPermission)}
	f.Func.SetPtrs(&f.Params.id, nil)
	return f
}

type RevokeDeployPermissionCall struct {
	Func *wasmlib.ScFunc
	Params MutableRevokeDeployPermissionParams
}

func NewRevokeDeployPermissionCall(ctx wasmlib.ScFuncContext) *RevokeDeployPermissionCall {
	f := &RevokeDeployPermissionCall{Func: wasmlib.NewScFunc(HScName, HFuncRevokeDeployPermission)}
	f.Func.SetPtrs(&f.Params.id, nil)
	return f
}

type SetContractFeeCall struct {
	Func *wasmlib.ScFunc
	Params MutableSetContractFeeParams
}

func NewSetContractFeeCall(ctx wasmlib.ScFuncContext) *SetContractFeeCall {
	f := &SetContractFeeCall{Func: wasmlib.NewScFunc(HScName, HFuncSetContractFee)}
	f.Func.SetPtrs(&f.Params.id, nil)
	return f
}

type SetDefaultFeeCall struct {
	Func *wasmlib.ScFunc
	Params MutableSetDefaultFeeParams
}

func NewSetDefaultFeeCall(ctx wasmlib.ScFuncContext) *SetDefaultFeeCall {
	f := &SetDefaultFeeCall{Func: wasmlib.NewScFunc(HScName, HFuncSetDefaultFee)}
	f.Func.SetPtrs(&f.Params.id, nil)
	return f
}

type FindContractCall struct {
	Func *wasmlib.ScView
	Params MutableFindContractParams
	Results ImmutableFindContractResults
}

func NewFindContractCall(ctx wasmlib.ScFuncContext) *FindContractCall {
	f := &FindContractCall{Func: wasmlib.NewScView(HScName, HViewFindContract)}
	f.Func.SetPtrs(&f.Params.id, &f.Results.id)
	return f
}

func NewFindContractCallFromView(ctx wasmlib.ScViewContext) *FindContractCall {
	return NewFindContractCall(wasmlib.ScFuncContext{})
}

type GetChainInfoCall struct {
	Func *wasmlib.ScView
	Results ImmutableGetChainInfoResults
}

func NewGetChainInfoCall(ctx wasmlib.ScFuncContext) *GetChainInfoCall {
	f := &GetChainInfoCall{Func: wasmlib.NewScView(HScName, HViewGetChainInfo)}
	f.Func.SetPtrs(nil, &f.Results.id)
	return f
}

func NewGetChainInfoCallFromView(ctx wasmlib.ScViewContext) *GetChainInfoCall {
	return NewGetChainInfoCall(wasmlib.ScFuncContext{})
}

type GetFeeInfoCall struct {
	Func *wasmlib.ScView
	Params MutableGetFeeInfoParams
	Results ImmutableGetFeeInfoResults
}

func NewGetFeeInfoCall(ctx wasmlib.ScFuncContext) *GetFeeInfoCall {
	f := &GetFeeInfoCall{Func: wasmlib.NewScView(HScName, HViewGetFeeInfo)}
	f.Func.SetPtrs(&f.Params.id, &f.Results.id)
	return f
}

func NewGetFeeInfoCallFromView(ctx wasmlib.ScViewContext) *GetFeeInfoCall {
	return NewGetFeeInfoCall(wasmlib.ScFuncContext{})
}
