// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

package erc20

import "github.com/iotaledger/wasplib/packages/vm/wasmlib"

type ImmutableApproveParams struct {
	id int32
}

func (s ImmutableApproveParams) Amount() wasmlib.ScImmutableInt64 {
	return wasmlib.NewScImmutableInt64(s.id, idxMap[IdxParamAmount])
}

func (s ImmutableApproveParams) Delegation() wasmlib.ScImmutableAgentId {
	return wasmlib.NewScImmutableAgentId(s.id, idxMap[IdxParamDelegation])
}

type MutableApproveParams struct {
	id int32
}

func (s MutableApproveParams) Amount() wasmlib.ScMutableInt64 {
	return wasmlib.NewScMutableInt64(s.id, idxMap[IdxParamAmount])
}

func (s MutableApproveParams) Delegation() wasmlib.ScMutableAgentId {
	return wasmlib.NewScMutableAgentId(s.id, idxMap[IdxParamDelegation])
}

type ImmutableInitParams struct {
	id int32
}

func (s ImmutableInitParams) Creator() wasmlib.ScImmutableAgentId {
	return wasmlib.NewScImmutableAgentId(s.id, idxMap[IdxParamCreator])
}

func (s ImmutableInitParams) Supply() wasmlib.ScImmutableInt64 {
	return wasmlib.NewScImmutableInt64(s.id, idxMap[IdxParamSupply])
}

type MutableInitParams struct {
	id int32
}

func (s MutableInitParams) Creator() wasmlib.ScMutableAgentId {
	return wasmlib.NewScMutableAgentId(s.id, idxMap[IdxParamCreator])
}

func (s MutableInitParams) Supply() wasmlib.ScMutableInt64 {
	return wasmlib.NewScMutableInt64(s.id, idxMap[IdxParamSupply])
}

type ImmutableTransferParams struct {
	id int32
}

func (s ImmutableTransferParams) Account() wasmlib.ScImmutableAgentId {
	return wasmlib.NewScImmutableAgentId(s.id, idxMap[IdxParamAccount])
}

func (s ImmutableTransferParams) Amount() wasmlib.ScImmutableInt64 {
	return wasmlib.NewScImmutableInt64(s.id, idxMap[IdxParamAmount])
}

type MutableTransferParams struct {
	id int32
}

func (s MutableTransferParams) Account() wasmlib.ScMutableAgentId {
	return wasmlib.NewScMutableAgentId(s.id, idxMap[IdxParamAccount])
}

func (s MutableTransferParams) Amount() wasmlib.ScMutableInt64 {
	return wasmlib.NewScMutableInt64(s.id, idxMap[IdxParamAmount])
}

type ImmutableTransferFromParams struct {
	id int32
}

func (s ImmutableTransferFromParams) Account() wasmlib.ScImmutableAgentId {
	return wasmlib.NewScImmutableAgentId(s.id, idxMap[IdxParamAccount])
}

func (s ImmutableTransferFromParams) Amount() wasmlib.ScImmutableInt64 {
	return wasmlib.NewScImmutableInt64(s.id, idxMap[IdxParamAmount])
}

func (s ImmutableTransferFromParams) Recipient() wasmlib.ScImmutableAgentId {
	return wasmlib.NewScImmutableAgentId(s.id, idxMap[IdxParamRecipient])
}

type MutableTransferFromParams struct {
	id int32
}

func (s MutableTransferFromParams) Account() wasmlib.ScMutableAgentId {
	return wasmlib.NewScMutableAgentId(s.id, idxMap[IdxParamAccount])
}

func (s MutableTransferFromParams) Amount() wasmlib.ScMutableInt64 {
	return wasmlib.NewScMutableInt64(s.id, idxMap[IdxParamAmount])
}

func (s MutableTransferFromParams) Recipient() wasmlib.ScMutableAgentId {
	return wasmlib.NewScMutableAgentId(s.id, idxMap[IdxParamRecipient])
}

type ImmutableAllowanceParams struct {
	id int32
}

func (s ImmutableAllowanceParams) Account() wasmlib.ScImmutableAgentId {
	return wasmlib.NewScImmutableAgentId(s.id, idxMap[IdxParamAccount])
}

func (s ImmutableAllowanceParams) Delegation() wasmlib.ScImmutableAgentId {
	return wasmlib.NewScImmutableAgentId(s.id, idxMap[IdxParamDelegation])
}

type MutableAllowanceParams struct {
	id int32
}

func (s MutableAllowanceParams) Account() wasmlib.ScMutableAgentId {
	return wasmlib.NewScMutableAgentId(s.id, idxMap[IdxParamAccount])
}

func (s MutableAllowanceParams) Delegation() wasmlib.ScMutableAgentId {
	return wasmlib.NewScMutableAgentId(s.id, idxMap[IdxParamDelegation])
}

type ImmutableBalanceOfParams struct {
	id int32
}

func (s ImmutableBalanceOfParams) Account() wasmlib.ScImmutableAgentId {
	return wasmlib.NewScImmutableAgentId(s.id, idxMap[IdxParamAccount])
}

type MutableBalanceOfParams struct {
	id int32
}

func (s MutableBalanceOfParams) Account() wasmlib.ScMutableAgentId {
	return wasmlib.NewScMutableAgentId(s.id, idxMap[IdxParamAccount])
}
