// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

#![allow(dead_code)]
#![allow(unused_imports)]

use wasmlib::*;
use wasmlib::host::*;

use crate::*;
use crate::keys::*;

pub struct MutableFuncHelloWorldParams {
    pub(crate) id: i32,
}

pub struct ImmutableFuncHelloWorldParams {
    pub(crate) id: i32,
}

pub struct MutableViewGetHelloWorldParams {
    pub(crate) id: i32,
}

pub struct ImmutableViewGetHelloWorldParams {
    pub(crate) id: i32,
}
