// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

package test

import "github.com/iotaledger/wasp/packages/coretypes"

const (
	ScName = "helloworld"
	ScDescription = "The ubiquitous hello world demo"
	HScName = coretypes.Hname(0x0683223c)

	ResultHelloWorld = "helloWorld"

	FuncHelloWorld = "helloWorld"
	ViewGetHelloWorld = "getHelloWorld"

	HFuncHelloWorld = coretypes.Hname(0x9d042e65)
	HViewGetHelloWorld = coretypes.Hname(0x210439ce)
)
