// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

package coreblocklog

import "github.com/iotaledger/wasplib/packages/vm/wasmlib"

const (
	ScName        = "blocklog"
	ScDescription = "Core block log contract"
	HScName       = wasmlib.ScHname(0xf538ef2b)

	ParamBlockIndex = wasmlib.Key("n")
	ParamRequestID  = wasmlib.Key("u")

	ResultBlockIndex       = wasmlib.Key("n")
	ResultBlockInfo        = wasmlib.Key("i")
	ResultRequestIndex     = wasmlib.Key("r")
	ResultRequestProcessed = wasmlib.Key("p")
	ResultRequestRecord    = wasmlib.Key("d")

	ViewGetBlockInfo                 = "getBlockInfo"
	ViewGetLatestBlockInfo           = "getLatestBlockInfo"
	ViewGetRequestIDsForBlock        = "getRequestIDsForBlock"
	ViewGetRequestLogRecord          = "getRequestLogRecord"
	ViewGetRequestLogRecordsForBlock = "getRequestLogRecordsForBlock"
	ViewIsRequestProcessed           = "isRequestProcessed"

	HViewGetBlockInfo                 = wasmlib.ScHname(0xbe89f9b3)
	HViewGetLatestBlockInfo           = wasmlib.ScHname(0x084a1760)
	HViewGetRequestIDsForBlock        = wasmlib.ScHname(0x5a20327a)
	HViewGetRequestLogRecord          = wasmlib.ScHname(0x31e07e48)
	HViewGetRequestLogRecordsForBlock = wasmlib.ScHname(0x7210e621)
	HViewIsRequestProcessed           = wasmlib.ScHname(0xd57d50a9)
)
