// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

package coreblocklog

import "github.com/iotaledger/wasplib/packages/vm/wasmlib"

type ImmutableViewGetBlockInfoParams struct {
	id int32
}

func (s ImmutableViewGetBlockInfoParams) BlockIndex() wasmlib.ScImmutableInt64 {
	return wasmlib.NewScImmutableInt64(s.id, ParamBlockIndex.KeyId())
}

type MutableViewGetBlockInfoParams struct {
	id int32
}

func NewMutableViewGetBlockInfoParams() MutableViewGetBlockInfoParams {
	return MutableViewGetBlockInfoParams{id: wasmlib.NewScMutableMap().MapId()}
}

func (s MutableViewGetBlockInfoParams) BlockIndex() wasmlib.ScMutableInt64 {
	return wasmlib.NewScMutableInt64(s.id, ParamBlockIndex.KeyId())
}

type ImmutableViewGetRequestIDsForBlockParams struct {
	id int32
}

func (s ImmutableViewGetRequestIDsForBlockParams) BlockIndex() wasmlib.ScImmutableInt64 {
	return wasmlib.NewScImmutableInt64(s.id, ParamBlockIndex.KeyId())
}

type MutableViewGetRequestIDsForBlockParams struct {
	id int32
}

func NewMutableViewGetRequestIDsForBlockParams() MutableViewGetRequestIDsForBlockParams {
	return MutableViewGetRequestIDsForBlockParams{id: wasmlib.NewScMutableMap().MapId()}
}

func (s MutableViewGetRequestIDsForBlockParams) BlockIndex() wasmlib.ScMutableInt64 {
	return wasmlib.NewScMutableInt64(s.id, ParamBlockIndex.KeyId())
}

type ImmutableViewGetRequestLogRecordParams struct {
	id int32
}

func (s ImmutableViewGetRequestLogRecordParams) RequestID() wasmlib.ScImmutableRequestId {
	return wasmlib.NewScImmutableRequestId(s.id, ParamRequestID.KeyId())
}

type MutableViewGetRequestLogRecordParams struct {
	id int32
}

func NewMutableViewGetRequestLogRecordParams() MutableViewGetRequestLogRecordParams {
	return MutableViewGetRequestLogRecordParams{id: wasmlib.NewScMutableMap().MapId()}
}

func (s MutableViewGetRequestLogRecordParams) RequestID() wasmlib.ScMutableRequestId {
	return wasmlib.NewScMutableRequestId(s.id, ParamRequestID.KeyId())
}

type ImmutableViewGetRequestLogRecordsForBlockParams struct {
	id int32
}

func (s ImmutableViewGetRequestLogRecordsForBlockParams) BlockIndex() wasmlib.ScImmutableInt64 {
	return wasmlib.NewScImmutableInt64(s.id, ParamBlockIndex.KeyId())
}

type MutableViewGetRequestLogRecordsForBlockParams struct {
	id int32
}

func NewMutableViewGetRequestLogRecordsForBlockParams() MutableViewGetRequestLogRecordsForBlockParams {
	return MutableViewGetRequestLogRecordsForBlockParams{id: wasmlib.NewScMutableMap().MapId()}
}

func (s MutableViewGetRequestLogRecordsForBlockParams) BlockIndex() wasmlib.ScMutableInt64 {
	return wasmlib.NewScMutableInt64(s.id, ParamBlockIndex.KeyId())
}

type ImmutableViewIsRequestProcessedParams struct {
	id int32
}

func (s ImmutableViewIsRequestProcessedParams) RequestID() wasmlib.ScImmutableRequestId {
	return wasmlib.NewScImmutableRequestId(s.id, ParamRequestID.KeyId())
}

type MutableViewIsRequestProcessedParams struct {
	id int32
}

func NewMutableViewIsRequestProcessedParams() MutableViewIsRequestProcessedParams {
	return MutableViewIsRequestProcessedParams{id: wasmlib.NewScMutableMap().MapId()}
}

func (s MutableViewIsRequestProcessedParams) RequestID() wasmlib.ScMutableRequestId {
	return wasmlib.NewScMutableRequestId(s.id, ParamRequestID.KeyId())
}
