// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

package org.iota.wasp.contracts.helloworld.lib;

import de.mirkosertic.bytecoder.api.*;
import org.iota.wasp.contracts.helloworld.*;
import org.iota.wasp.wasmlib.context.*;
import org.iota.wasp.wasmlib.exports.*;
import org.iota.wasp.wasmlib.immutable.*;

public class HelloWorldThunk {
    public static void main(String[] args) {
    }

    @Export("on_load")
    public static void onLoad() {
        ScExports exports = new ScExports();
        exports.AddFunc(Consts.FuncHelloWorld, HelloWorldThunk::funcHelloWorldThunk);
        exports.AddView(Consts.ViewGetHelloWorld, HelloWorldThunk::viewGetHelloWorldThunk);
    }

    private static void funcHelloWorldThunk(ScFuncContext ctx) {
        ctx.Log("helloworld.funcHelloWorld");
        var params = new FuncHelloWorldParams();
        HelloWorld.funcHelloWorld(ctx, params);
        ctx.Log("helloworld.funcHelloWorld ok");
    }

    private static void viewGetHelloWorldThunk(ScViewContext ctx) {
        ctx.Log("helloworld.viewGetHelloWorld");
        var params = new ViewGetHelloWorldParams();
        HelloWorld.viewGetHelloWorld(ctx, params);
        ctx.Log("helloworld.viewGetHelloWorld ok");
    }
}
