// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

package tokenregistry

import "github.com/iotaledger/wasplib/packages/vm/wasmlib"

type MutableFuncMintSupplyParams struct {
	id int32
}

func (s MutableFuncMintSupplyParams) Description() wasmlib.ScMutableString {
	return wasmlib.NewScMutableString(s.id, idxMap[IdxParamDescription])
}

func (s MutableFuncMintSupplyParams) UserDefined() wasmlib.ScMutableString {
	return wasmlib.NewScMutableString(s.id, idxMap[IdxParamUserDefined])
}

type ImmutableFuncMintSupplyParams struct {
	id int32
}

func (s ImmutableFuncMintSupplyParams) Description() wasmlib.ScImmutableString {
	return wasmlib.NewScImmutableString(s.id, idxMap[IdxParamDescription])
}

func (s ImmutableFuncMintSupplyParams) UserDefined() wasmlib.ScImmutableString {
	return wasmlib.NewScImmutableString(s.id, idxMap[IdxParamUserDefined])
}

type MutableFuncTransferOwnershipParams struct {
	id int32
}

func (s MutableFuncTransferOwnershipParams) Color() wasmlib.ScMutableColor {
	return wasmlib.NewScMutableColor(s.id, idxMap[IdxParamColor])
}

type ImmutableFuncTransferOwnershipParams struct {
	id int32
}

func (s ImmutableFuncTransferOwnershipParams) Color() wasmlib.ScImmutableColor {
	return wasmlib.NewScImmutableColor(s.id, idxMap[IdxParamColor])
}

type MutableFuncUpdateMetadataParams struct {
	id int32
}

func (s MutableFuncUpdateMetadataParams) Color() wasmlib.ScMutableColor {
	return wasmlib.NewScMutableColor(s.id, idxMap[IdxParamColor])
}

type ImmutableFuncUpdateMetadataParams struct {
	id int32
}

func (s ImmutableFuncUpdateMetadataParams) Color() wasmlib.ScImmutableColor {
	return wasmlib.NewScImmutableColor(s.id, idxMap[IdxParamColor])
}

type MutableViewGetInfoParams struct {
	id int32
}

func (s MutableViewGetInfoParams) Color() wasmlib.ScMutableColor {
	return wasmlib.NewScMutableColor(s.id, idxMap[IdxParamColor])
}

type ImmutableViewGetInfoParams struct {
	id int32
}

func (s ImmutableViewGetInfoParams) Color() wasmlib.ScImmutableColor {
	return wasmlib.NewScImmutableColor(s.id, idxMap[IdxParamColor])
}
