// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

package tokenregistry

import "github.com/iotaledger/wasplib/packages/vm/wasmlib"

type ArrayOfMutableColor struct {
	objId int32
}

func (a ArrayOfMutableColor) Clear() {
	wasmlib.Clear(a.objId)
}

func (a ArrayOfMutableColor) Length() int32 {
	return wasmlib.GetLength(a.objId)
}

func (a ArrayOfMutableColor) GetColor(index int32) wasmlib.ScMutableColor {
	return wasmlib.NewScMutableColor(a.objId, wasmlib.Key32(index))
}

type MapColorToMutableToken struct {
	objId int32
}

func (m MapColorToMutableToken) Clear() {
	wasmlib.Clear(m.objId)
}

func (m MapColorToMutableToken) GetToken(key wasmlib.ScColor) MutableToken {
	return MutableToken{objId: m.objId, keyId: key.KeyId()}
}

type TokenRegistryFuncState struct {
	stateId int32
}

func (s TokenRegistryFuncState) ColorList() ArrayOfMutableColor {
	arrId := wasmlib.GetObjectId(s.stateId, idxMap[IdxVarColorList], wasmlib.TYPE_ARRAY|wasmlib.TYPE_COLOR)
	return ArrayOfMutableColor{objId: arrId}
}

func (s TokenRegistryFuncState) Registry() MapColorToMutableToken {
	mapId := wasmlib.GetObjectId(s.stateId, idxMap[IdxVarRegistry], wasmlib.TYPE_MAP)
	return MapColorToMutableToken{objId: mapId}
}

type ArrayOfImmutableColor struct {
	objId int32
}

func (a ArrayOfImmutableColor) Length() int32 {
	return wasmlib.GetLength(a.objId)
}

func (a ArrayOfImmutableColor) GetColor(index int32) wasmlib.ScImmutableColor {
	return wasmlib.NewScImmutableColor(a.objId, wasmlib.Key32(index))
}

type MapColorToImmutableToken struct {
	objId int32
}

func (m MapColorToImmutableToken) GetToken(key wasmlib.ScColor) ImmutableToken {
	return ImmutableToken{objId: m.objId, keyId: key.KeyId()}
}

type TokenRegistryViewState struct {
	stateId int32
}

func (s TokenRegistryViewState) ColorList() ArrayOfImmutableColor {
	arrId := wasmlib.GetObjectId(s.stateId, idxMap[IdxVarColorList], wasmlib.TYPE_ARRAY|wasmlib.TYPE_COLOR)
	return ArrayOfImmutableColor{objId: arrId}
}

func (s TokenRegistryViewState) Registry() MapColorToImmutableToken {
	mapId := wasmlib.GetObjectId(s.stateId, idxMap[IdxVarRegistry], wasmlib.TYPE_MAP)
	return MapColorToImmutableToken{objId: mapId}
}
