// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

package fairauction

import "github.com/iotaledger/wasplib/packages/vm/wasmlib"

type MutableFuncFinalizeAuctionParams struct {
	id int32
}

func (s MutableFuncFinalizeAuctionParams) Color() wasmlib.ScMutableColor {
	return wasmlib.NewScMutableColor(s.id, idxMap[IdxParamColor])
}

type ImmutableFuncFinalizeAuctionParams struct {
	id int32
}

func (s ImmutableFuncFinalizeAuctionParams) Color() wasmlib.ScImmutableColor {
	return wasmlib.NewScImmutableColor(s.id, idxMap[IdxParamColor])
}

type MutableFuncPlaceBidParams struct {
	id int32
}

func (s MutableFuncPlaceBidParams) Color() wasmlib.ScMutableColor {
	return wasmlib.NewScMutableColor(s.id, idxMap[IdxParamColor])
}

type ImmutableFuncPlaceBidParams struct {
	id int32
}

func (s ImmutableFuncPlaceBidParams) Color() wasmlib.ScImmutableColor {
	return wasmlib.NewScImmutableColor(s.id, idxMap[IdxParamColor])
}

type MutableFuncSetOwnerMarginParams struct {
	id int32
}

func (s MutableFuncSetOwnerMarginParams) OwnerMargin() wasmlib.ScMutableInt64 {
	return wasmlib.NewScMutableInt64(s.id, idxMap[IdxParamOwnerMargin])
}

type ImmutableFuncSetOwnerMarginParams struct {
	id int32
}

func (s ImmutableFuncSetOwnerMarginParams) OwnerMargin() wasmlib.ScImmutableInt64 {
	return wasmlib.NewScImmutableInt64(s.id, idxMap[IdxParamOwnerMargin])
}

type MutableFuncStartAuctionParams struct {
	id int32
}

func (s MutableFuncStartAuctionParams) Color() wasmlib.ScMutableColor {
	return wasmlib.NewScMutableColor(s.id, idxMap[IdxParamColor])
}

func (s MutableFuncStartAuctionParams) Description() wasmlib.ScMutableString {
	return wasmlib.NewScMutableString(s.id, idxMap[IdxParamDescription])
}

func (s MutableFuncStartAuctionParams) Duration() wasmlib.ScMutableInt64 {
	return wasmlib.NewScMutableInt64(s.id, idxMap[IdxParamDuration])
}

func (s MutableFuncStartAuctionParams) MinimumBid() wasmlib.ScMutableInt64 {
	return wasmlib.NewScMutableInt64(s.id, idxMap[IdxParamMinimumBid])
}

type ImmutableFuncStartAuctionParams struct {
	id int32
}

func (s ImmutableFuncStartAuctionParams) Color() wasmlib.ScImmutableColor {
	return wasmlib.NewScImmutableColor(s.id, idxMap[IdxParamColor])
}

func (s ImmutableFuncStartAuctionParams) Description() wasmlib.ScImmutableString {
	return wasmlib.NewScImmutableString(s.id, idxMap[IdxParamDescription])
}

func (s ImmutableFuncStartAuctionParams) Duration() wasmlib.ScImmutableInt64 {
	return wasmlib.NewScImmutableInt64(s.id, idxMap[IdxParamDuration])
}

func (s ImmutableFuncStartAuctionParams) MinimumBid() wasmlib.ScImmutableInt64 {
	return wasmlib.NewScImmutableInt64(s.id, idxMap[IdxParamMinimumBid])
}

type MutableViewGetInfoParams struct {
	id int32
}

func (s MutableViewGetInfoParams) Color() wasmlib.ScMutableColor {
	return wasmlib.NewScMutableColor(s.id, idxMap[IdxParamColor])
}

type ImmutableViewGetInfoParams struct {
	id int32
}

func (s ImmutableViewGetInfoParams) Color() wasmlib.ScImmutableColor {
	return wasmlib.NewScImmutableColor(s.id, idxMap[IdxParamColor])
}
