// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

package testcore

import "github.com/iotaledger/wasplib/packages/vm/wasmlib"

type ImmutableCallOnChainParams struct {
	id int32
}

func (s ImmutableCallOnChainParams) HnameContract() wasmlib.ScImmutableHname {
	return wasmlib.NewScImmutableHname(s.id, idxMap[IdxParamHnameContract])
}

func (s ImmutableCallOnChainParams) HnameEP() wasmlib.ScImmutableHname {
	return wasmlib.NewScImmutableHname(s.id, idxMap[IdxParamHnameEP])
}

func (s ImmutableCallOnChainParams) IntValue() wasmlib.ScImmutableInt64 {
	return wasmlib.NewScImmutableInt64(s.id, idxMap[IdxParamIntValue])
}

type MutableCallOnChainParams struct {
	id int32
}

func (s MutableCallOnChainParams) HnameContract() wasmlib.ScMutableHname {
	return wasmlib.NewScMutableHname(s.id, idxMap[IdxParamHnameContract])
}

func (s MutableCallOnChainParams) HnameEP() wasmlib.ScMutableHname {
	return wasmlib.NewScMutableHname(s.id, idxMap[IdxParamHnameEP])
}

func (s MutableCallOnChainParams) IntValue() wasmlib.ScMutableInt64 {
	return wasmlib.NewScMutableInt64(s.id, idxMap[IdxParamIntValue])
}

type ImmutableCheckContextFromFullEPParams struct {
	id int32
}

func (s ImmutableCheckContextFromFullEPParams) AgentId() wasmlib.ScImmutableAgentId {
	return wasmlib.NewScImmutableAgentId(s.id, idxMap[IdxParamAgentId])
}

func (s ImmutableCheckContextFromFullEPParams) Caller() wasmlib.ScImmutableAgentId {
	return wasmlib.NewScImmutableAgentId(s.id, idxMap[IdxParamCaller])
}

func (s ImmutableCheckContextFromFullEPParams) ChainId() wasmlib.ScImmutableChainId {
	return wasmlib.NewScImmutableChainId(s.id, idxMap[IdxParamChainId])
}

func (s ImmutableCheckContextFromFullEPParams) ChainOwnerId() wasmlib.ScImmutableAgentId {
	return wasmlib.NewScImmutableAgentId(s.id, idxMap[IdxParamChainOwnerId])
}

func (s ImmutableCheckContextFromFullEPParams) ContractCreator() wasmlib.ScImmutableAgentId {
	return wasmlib.NewScImmutableAgentId(s.id, idxMap[IdxParamContractCreator])
}

type MutableCheckContextFromFullEPParams struct {
	id int32
}

func (s MutableCheckContextFromFullEPParams) AgentId() wasmlib.ScMutableAgentId {
	return wasmlib.NewScMutableAgentId(s.id, idxMap[IdxParamAgentId])
}

func (s MutableCheckContextFromFullEPParams) Caller() wasmlib.ScMutableAgentId {
	return wasmlib.NewScMutableAgentId(s.id, idxMap[IdxParamCaller])
}

func (s MutableCheckContextFromFullEPParams) ChainId() wasmlib.ScMutableChainId {
	return wasmlib.NewScMutableChainId(s.id, idxMap[IdxParamChainId])
}

func (s MutableCheckContextFromFullEPParams) ChainOwnerId() wasmlib.ScMutableAgentId {
	return wasmlib.NewScMutableAgentId(s.id, idxMap[IdxParamChainOwnerId])
}

func (s MutableCheckContextFromFullEPParams) ContractCreator() wasmlib.ScMutableAgentId {
	return wasmlib.NewScMutableAgentId(s.id, idxMap[IdxParamContractCreator])
}

type ImmutablePassTypesFullParams struct {
	id int32
}

func (s ImmutablePassTypesFullParams) Hash() wasmlib.ScImmutableHash {
	return wasmlib.NewScImmutableHash(s.id, idxMap[IdxParamHash])
}

func (s ImmutablePassTypesFullParams) Hname() wasmlib.ScImmutableHname {
	return wasmlib.NewScImmutableHname(s.id, idxMap[IdxParamHname])
}

func (s ImmutablePassTypesFullParams) HnameZero() wasmlib.ScImmutableHname {
	return wasmlib.NewScImmutableHname(s.id, idxMap[IdxParamHnameZero])
}

func (s ImmutablePassTypesFullParams) Int64() wasmlib.ScImmutableInt64 {
	return wasmlib.NewScImmutableInt64(s.id, idxMap[IdxParamInt64])
}

func (s ImmutablePassTypesFullParams) Int64Zero() wasmlib.ScImmutableInt64 {
	return wasmlib.NewScImmutableInt64(s.id, idxMap[IdxParamInt64Zero])
}

func (s ImmutablePassTypesFullParams) String() wasmlib.ScImmutableString {
	return wasmlib.NewScImmutableString(s.id, idxMap[IdxParamString])
}

func (s ImmutablePassTypesFullParams) StringZero() wasmlib.ScImmutableString {
	return wasmlib.NewScImmutableString(s.id, idxMap[IdxParamStringZero])
}

type MutablePassTypesFullParams struct {
	id int32
}

func (s MutablePassTypesFullParams) Hash() wasmlib.ScMutableHash {
	return wasmlib.NewScMutableHash(s.id, idxMap[IdxParamHash])
}

func (s MutablePassTypesFullParams) Hname() wasmlib.ScMutableHname {
	return wasmlib.NewScMutableHname(s.id, idxMap[IdxParamHname])
}

func (s MutablePassTypesFullParams) HnameZero() wasmlib.ScMutableHname {
	return wasmlib.NewScMutableHname(s.id, idxMap[IdxParamHnameZero])
}

func (s MutablePassTypesFullParams) Int64() wasmlib.ScMutableInt64 {
	return wasmlib.NewScMutableInt64(s.id, idxMap[IdxParamInt64])
}

func (s MutablePassTypesFullParams) Int64Zero() wasmlib.ScMutableInt64 {
	return wasmlib.NewScMutableInt64(s.id, idxMap[IdxParamInt64Zero])
}

func (s MutablePassTypesFullParams) String() wasmlib.ScMutableString {
	return wasmlib.NewScMutableString(s.id, idxMap[IdxParamString])
}

func (s MutablePassTypesFullParams) StringZero() wasmlib.ScMutableString {
	return wasmlib.NewScMutableString(s.id, idxMap[IdxParamStringZero])
}

type ImmutableRunRecursionParams struct {
	id int32
}

func (s ImmutableRunRecursionParams) IntValue() wasmlib.ScImmutableInt64 {
	return wasmlib.NewScImmutableInt64(s.id, idxMap[IdxParamIntValue])
}

type MutableRunRecursionParams struct {
	id int32
}

func (s MutableRunRecursionParams) IntValue() wasmlib.ScMutableInt64 {
	return wasmlib.NewScMutableInt64(s.id, idxMap[IdxParamIntValue])
}

type ImmutableSendToAddressParams struct {
	id int32
}

func (s ImmutableSendToAddressParams) Address() wasmlib.ScImmutableAddress {
	return wasmlib.NewScImmutableAddress(s.id, idxMap[IdxParamAddress])
}

type MutableSendToAddressParams struct {
	id int32
}

func (s MutableSendToAddressParams) Address() wasmlib.ScMutableAddress {
	return wasmlib.NewScMutableAddress(s.id, idxMap[IdxParamAddress])
}

type ImmutableSetIntParams struct {
	id int32
}

func (s ImmutableSetIntParams) IntValue() wasmlib.ScImmutableInt64 {
	return wasmlib.NewScImmutableInt64(s.id, idxMap[IdxParamIntValue])
}

func (s ImmutableSetIntParams) Name() wasmlib.ScImmutableString {
	return wasmlib.NewScImmutableString(s.id, idxMap[IdxParamName])
}

type MutableSetIntParams struct {
	id int32
}

func (s MutableSetIntParams) IntValue() wasmlib.ScMutableInt64 {
	return wasmlib.NewScMutableInt64(s.id, idxMap[IdxParamIntValue])
}

func (s MutableSetIntParams) Name() wasmlib.ScMutableString {
	return wasmlib.NewScMutableString(s.id, idxMap[IdxParamName])
}

type ImmutableTestEventLogGenericDataParams struct {
	id int32
}

func (s ImmutableTestEventLogGenericDataParams) Counter() wasmlib.ScImmutableInt64 {
	return wasmlib.NewScImmutableInt64(s.id, idxMap[IdxParamCounter])
}

type MutableTestEventLogGenericDataParams struct {
	id int32
}

func (s MutableTestEventLogGenericDataParams) Counter() wasmlib.ScMutableInt64 {
	return wasmlib.NewScMutableInt64(s.id, idxMap[IdxParamCounter])
}

type ImmutableWithdrawToChainParams struct {
	id int32
}

func (s ImmutableWithdrawToChainParams) ChainId() wasmlib.ScImmutableChainId {
	return wasmlib.NewScImmutableChainId(s.id, idxMap[IdxParamChainId])
}

type MutableWithdrawToChainParams struct {
	id int32
}

func (s MutableWithdrawToChainParams) ChainId() wasmlib.ScMutableChainId {
	return wasmlib.NewScMutableChainId(s.id, idxMap[IdxParamChainId])
}

type ImmutableCheckContextFromViewEPParams struct {
	id int32
}

func (s ImmutableCheckContextFromViewEPParams) AgentId() wasmlib.ScImmutableAgentId {
	return wasmlib.NewScImmutableAgentId(s.id, idxMap[IdxParamAgentId])
}

func (s ImmutableCheckContextFromViewEPParams) ChainId() wasmlib.ScImmutableChainId {
	return wasmlib.NewScImmutableChainId(s.id, idxMap[IdxParamChainId])
}

func (s ImmutableCheckContextFromViewEPParams) ChainOwnerId() wasmlib.ScImmutableAgentId {
	return wasmlib.NewScImmutableAgentId(s.id, idxMap[IdxParamChainOwnerId])
}

func (s ImmutableCheckContextFromViewEPParams) ContractCreator() wasmlib.ScImmutableAgentId {
	return wasmlib.NewScImmutableAgentId(s.id, idxMap[IdxParamContractCreator])
}

type MutableCheckContextFromViewEPParams struct {
	id int32
}

func (s MutableCheckContextFromViewEPParams) AgentId() wasmlib.ScMutableAgentId {
	return wasmlib.NewScMutableAgentId(s.id, idxMap[IdxParamAgentId])
}

func (s MutableCheckContextFromViewEPParams) ChainId() wasmlib.ScMutableChainId {
	return wasmlib.NewScMutableChainId(s.id, idxMap[IdxParamChainId])
}

func (s MutableCheckContextFromViewEPParams) ChainOwnerId() wasmlib.ScMutableAgentId {
	return wasmlib.NewScMutableAgentId(s.id, idxMap[IdxParamChainOwnerId])
}

func (s MutableCheckContextFromViewEPParams) ContractCreator() wasmlib.ScMutableAgentId {
	return wasmlib.NewScMutableAgentId(s.id, idxMap[IdxParamContractCreator])
}

type ImmutableFibonacciParams struct {
	id int32
}

func (s ImmutableFibonacciParams) IntValue() wasmlib.ScImmutableInt64 {
	return wasmlib.NewScImmutableInt64(s.id, idxMap[IdxParamIntValue])
}

type MutableFibonacciParams struct {
	id int32
}

func (s MutableFibonacciParams) IntValue() wasmlib.ScMutableInt64 {
	return wasmlib.NewScMutableInt64(s.id, idxMap[IdxParamIntValue])
}

type ImmutableGetIntParams struct {
	id int32
}

func (s ImmutableGetIntParams) Name() wasmlib.ScImmutableString {
	return wasmlib.NewScImmutableString(s.id, idxMap[IdxParamName])
}

type MutableGetIntParams struct {
	id int32
}

func (s MutableGetIntParams) Name() wasmlib.ScMutableString {
	return wasmlib.NewScMutableString(s.id, idxMap[IdxParamName])
}

type ImmutablePassTypesViewParams struct {
	id int32
}

func (s ImmutablePassTypesViewParams) Hash() wasmlib.ScImmutableHash {
	return wasmlib.NewScImmutableHash(s.id, idxMap[IdxParamHash])
}

func (s ImmutablePassTypesViewParams) Hname() wasmlib.ScImmutableHname {
	return wasmlib.NewScImmutableHname(s.id, idxMap[IdxParamHname])
}

func (s ImmutablePassTypesViewParams) HnameZero() wasmlib.ScImmutableHname {
	return wasmlib.NewScImmutableHname(s.id, idxMap[IdxParamHnameZero])
}

func (s ImmutablePassTypesViewParams) Int64() wasmlib.ScImmutableInt64 {
	return wasmlib.NewScImmutableInt64(s.id, idxMap[IdxParamInt64])
}

func (s ImmutablePassTypesViewParams) Int64Zero() wasmlib.ScImmutableInt64 {
	return wasmlib.NewScImmutableInt64(s.id, idxMap[IdxParamInt64Zero])
}

func (s ImmutablePassTypesViewParams) String() wasmlib.ScImmutableString {
	return wasmlib.NewScImmutableString(s.id, idxMap[IdxParamString])
}

func (s ImmutablePassTypesViewParams) StringZero() wasmlib.ScImmutableString {
	return wasmlib.NewScImmutableString(s.id, idxMap[IdxParamStringZero])
}

type MutablePassTypesViewParams struct {
	id int32
}

func (s MutablePassTypesViewParams) Hash() wasmlib.ScMutableHash {
	return wasmlib.NewScMutableHash(s.id, idxMap[IdxParamHash])
}

func (s MutablePassTypesViewParams) Hname() wasmlib.ScMutableHname {
	return wasmlib.NewScMutableHname(s.id, idxMap[IdxParamHname])
}

func (s MutablePassTypesViewParams) HnameZero() wasmlib.ScMutableHname {
	return wasmlib.NewScMutableHname(s.id, idxMap[IdxParamHnameZero])
}

func (s MutablePassTypesViewParams) Int64() wasmlib.ScMutableInt64 {
	return wasmlib.NewScMutableInt64(s.id, idxMap[IdxParamInt64])
}

func (s MutablePassTypesViewParams) Int64Zero() wasmlib.ScMutableInt64 {
	return wasmlib.NewScMutableInt64(s.id, idxMap[IdxParamInt64Zero])
}

func (s MutablePassTypesViewParams) String() wasmlib.ScMutableString {
	return wasmlib.NewScMutableString(s.id, idxMap[IdxParamString])
}

func (s MutablePassTypesViewParams) StringZero() wasmlib.ScMutableString {
	return wasmlib.NewScMutableString(s.id, idxMap[IdxParamStringZero])
}
