// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

#![allow(dead_code)]

use std::ptr;

use wasmlib::*;

use crate::consts::*;
use crate::params::*;
use crate::results::*;

pub struct CallOnChainCall {
    pub func: ScFunc,
    pub params: MutableCallOnChainParams,
    pub results: ImmutableCallOnChainResults,
}

impl CallOnChainCall {
    pub fn new(_ctx: &ScFuncContext) -> CallOnChainCall {
        let mut f = CallOnChainCall {
            func: ScFunc::zero(),
            params: MutableCallOnChainParams { id: 0 },
            results: ImmutableCallOnChainResults { id: 0 },
        };
        f.func = ScFunc::new(HSC_NAME, HFUNC_CALL_ON_CHAIN, &mut f.params.id, &mut f.results.id);
        f
    }
}

pub struct CheckContextFromFullEPCall {
    pub func: ScFunc,
    pub params: MutableCheckContextFromFullEPParams,
}

impl CheckContextFromFullEPCall {
    pub fn new(_ctx: &ScFuncContext) -> CheckContextFromFullEPCall {
        let mut f = CheckContextFromFullEPCall {
            func: ScFunc::zero(),
            params: MutableCheckContextFromFullEPParams { id: 0 },
        };
        f.func = ScFunc::new(HSC_NAME, HFUNC_CHECK_CONTEXT_FROM_FULL_EP, &mut f.params.id, ptr::null_mut());
        f
    }
}

pub struct DoNothingCall {
    pub func: ScFunc,
}

impl DoNothingCall {
    pub fn new(_ctx: &ScFuncContext) -> DoNothingCall {
        let mut f = DoNothingCall {
            func: ScFunc::zero(),
        };
        f.func = ScFunc::new(HSC_NAME, HFUNC_DO_NOTHING, ptr::null_mut(), ptr::null_mut());
        f
    }
}

pub struct GetMintedSupplyCall {
    pub func: ScFunc,
    pub results: ImmutableGetMintedSupplyResults,
}

impl GetMintedSupplyCall {
    pub fn new(_ctx: &ScFuncContext) -> GetMintedSupplyCall {
        let mut f = GetMintedSupplyCall {
            func: ScFunc::zero(),
            results: ImmutableGetMintedSupplyResults { id: 0 },
        };
        f.func = ScFunc::new(HSC_NAME, HFUNC_GET_MINTED_SUPPLY, ptr::null_mut(), &mut f.results.id);
        f
    }
}

pub struct IncCounterCall {
    pub func: ScFunc,
}

impl IncCounterCall {
    pub fn new(_ctx: &ScFuncContext) -> IncCounterCall {
        let mut f = IncCounterCall {
            func: ScFunc::zero(),
        };
        f.func = ScFunc::new(HSC_NAME, HFUNC_INC_COUNTER, ptr::null_mut(), ptr::null_mut());
        f
    }
}

pub struct InitCall {
    pub func: ScFunc,
}

impl InitCall {
    pub fn new(_ctx: &ScFuncContext) -> InitCall {
        let mut f = InitCall {
            func: ScFunc::zero(),
        };
        f.func = ScFunc::new(HSC_NAME, HFUNC_INIT, ptr::null_mut(), ptr::null_mut());
        f
    }
}

pub struct PassTypesFullCall {
    pub func: ScFunc,
    pub params: MutablePassTypesFullParams,
}

impl PassTypesFullCall {
    pub fn new(_ctx: &ScFuncContext) -> PassTypesFullCall {
        let mut f = PassTypesFullCall {
            func: ScFunc::zero(),
            params: MutablePassTypesFullParams { id: 0 },
        };
        f.func = ScFunc::new(HSC_NAME, HFUNC_PASS_TYPES_FULL, &mut f.params.id, ptr::null_mut());
        f
    }
}

pub struct RunRecursionCall {
    pub func: ScFunc,
    pub params: MutableRunRecursionParams,
    pub results: ImmutableRunRecursionResults,
}

impl RunRecursionCall {
    pub fn new(_ctx: &ScFuncContext) -> RunRecursionCall {
        let mut f = RunRecursionCall {
            func: ScFunc::zero(),
            params: MutableRunRecursionParams { id: 0 },
            results: ImmutableRunRecursionResults { id: 0 },
        };
        f.func = ScFunc::new(HSC_NAME, HFUNC_RUN_RECURSION, &mut f.params.id, &mut f.results.id);
        f
    }
}

pub struct SendToAddressCall {
    pub func: ScFunc,
    pub params: MutableSendToAddressParams,
}

impl SendToAddressCall {
    pub fn new(_ctx: &ScFuncContext) -> SendToAddressCall {
        let mut f = SendToAddressCall {
            func: ScFunc::zero(),
            params: MutableSendToAddressParams { id: 0 },
        };
        f.func = ScFunc::new(HSC_NAME, HFUNC_SEND_TO_ADDRESS, &mut f.params.id, ptr::null_mut());
        f
    }
}

pub struct SetIntCall {
    pub func: ScFunc,
    pub params: MutableSetIntParams,
}

impl SetIntCall {
    pub fn new(_ctx: &ScFuncContext) -> SetIntCall {
        let mut f = SetIntCall {
            func: ScFunc::zero(),
            params: MutableSetIntParams { id: 0 },
        };
        f.func = ScFunc::new(HSC_NAME, HFUNC_SET_INT, &mut f.params.id, ptr::null_mut());
        f
    }
}

pub struct TestCallPanicFullEPCall {
    pub func: ScFunc,
}

impl TestCallPanicFullEPCall {
    pub fn new(_ctx: &ScFuncContext) -> TestCallPanicFullEPCall {
        let mut f = TestCallPanicFullEPCall {
            func: ScFunc::zero(),
        };
        f.func = ScFunc::new(HSC_NAME, HFUNC_TEST_CALL_PANIC_FULL_EP, ptr::null_mut(), ptr::null_mut());
        f
    }
}

pub struct TestCallPanicViewEPFromFullCall {
    pub func: ScFunc,
}

impl TestCallPanicViewEPFromFullCall {
    pub fn new(_ctx: &ScFuncContext) -> TestCallPanicViewEPFromFullCall {
        let mut f = TestCallPanicViewEPFromFullCall {
            func: ScFunc::zero(),
        };
        f.func = ScFunc::new(HSC_NAME, HFUNC_TEST_CALL_PANIC_VIEW_EP_FROM_FULL, ptr::null_mut(), ptr::null_mut());
        f
    }
}

pub struct TestChainOwnerIDFullCall {
    pub func: ScFunc,
    pub results: ImmutableTestChainOwnerIDFullResults,
}

impl TestChainOwnerIDFullCall {
    pub fn new(_ctx: &ScFuncContext) -> TestChainOwnerIDFullCall {
        let mut f = TestChainOwnerIDFullCall {
            func: ScFunc::zero(),
            results: ImmutableTestChainOwnerIDFullResults { id: 0 },
        };
        f.func = ScFunc::new(HSC_NAME, HFUNC_TEST_CHAIN_OWNER_ID_FULL, ptr::null_mut(), &mut f.results.id);
        f
    }
}

pub struct TestEventLogDeployCall {
    pub func: ScFunc,
}

impl TestEventLogDeployCall {
    pub fn new(_ctx: &ScFuncContext) -> TestEventLogDeployCall {
        let mut f = TestEventLogDeployCall {
            func: ScFunc::zero(),
        };
        f.func = ScFunc::new(HSC_NAME, HFUNC_TEST_EVENT_LOG_DEPLOY, ptr::null_mut(), ptr::null_mut());
        f
    }
}

pub struct TestEventLogEventDataCall {
    pub func: ScFunc,
}

impl TestEventLogEventDataCall {
    pub fn new(_ctx: &ScFuncContext) -> TestEventLogEventDataCall {
        let mut f = TestEventLogEventDataCall {
            func: ScFunc::zero(),
        };
        f.func = ScFunc::new(HSC_NAME, HFUNC_TEST_EVENT_LOG_EVENT_DATA, ptr::null_mut(), ptr::null_mut());
        f
    }
}

pub struct TestEventLogGenericDataCall {
    pub func: ScFunc,
    pub params: MutableTestEventLogGenericDataParams,
}

impl TestEventLogGenericDataCall {
    pub fn new(_ctx: &ScFuncContext) -> TestEventLogGenericDataCall {
        let mut f = TestEventLogGenericDataCall {
            func: ScFunc::zero(),
            params: MutableTestEventLogGenericDataParams { id: 0 },
        };
        f.func = ScFunc::new(HSC_NAME, HFUNC_TEST_EVENT_LOG_GENERIC_DATA, &mut f.params.id, ptr::null_mut());
        f
    }
}

pub struct TestPanicFullEPCall {
    pub func: ScFunc,
}

impl TestPanicFullEPCall {
    pub fn new(_ctx: &ScFuncContext) -> TestPanicFullEPCall {
        let mut f = TestPanicFullEPCall {
            func: ScFunc::zero(),
        };
        f.func = ScFunc::new(HSC_NAME, HFUNC_TEST_PANIC_FULL_EP, ptr::null_mut(), ptr::null_mut());
        f
    }
}

pub struct WithdrawToChainCall {
    pub func: ScFunc,
    pub params: MutableWithdrawToChainParams,
}

impl WithdrawToChainCall {
    pub fn new(_ctx: &ScFuncContext) -> WithdrawToChainCall {
        let mut f = WithdrawToChainCall {
            func: ScFunc::zero(),
            params: MutableWithdrawToChainParams { id: 0 },
        };
        f.func = ScFunc::new(HSC_NAME, HFUNC_WITHDRAW_TO_CHAIN, &mut f.params.id, ptr::null_mut());
        f
    }
}

pub struct CheckContextFromViewEPCall {
    pub func: ScView,
    pub params: MutableCheckContextFromViewEPParams,
}

impl CheckContextFromViewEPCall {
    pub fn new(_ctx: &ScFuncContext) -> CheckContextFromViewEPCall {
        let mut f = CheckContextFromViewEPCall {
            func: ScView::zero(),
            params: MutableCheckContextFromViewEPParams { id: 0 },
        };
        f.func = ScView::new(HSC_NAME, HVIEW_CHECK_CONTEXT_FROM_VIEW_EP, &mut f.params.id, ptr::null_mut());
        f
    }

    pub fn new_from_view(_ctx: &ScViewContext) -> CheckContextFromViewEPCall {
        let mut f = CheckContextFromViewEPCall {
            func: ScView::zero(),
            params: MutableCheckContextFromViewEPParams { id: 0 },
        };
        f.func = ScView::new(HSC_NAME, HVIEW_CHECK_CONTEXT_FROM_VIEW_EP, &mut f.params.id, ptr::null_mut());
        f
    }
}

pub struct FibonacciCall {
    pub func: ScView,
    pub params: MutableFibonacciParams,
    pub results: ImmutableFibonacciResults,
}

impl FibonacciCall {
    pub fn new(_ctx: &ScFuncContext) -> FibonacciCall {
        let mut f = FibonacciCall {
            func: ScView::zero(),
            params: MutableFibonacciParams { id: 0 },
            results: ImmutableFibonacciResults { id: 0 },
        };
        f.func = ScView::new(HSC_NAME, HVIEW_FIBONACCI, &mut f.params.id, &mut f.results.id);
        f
    }

    pub fn new_from_view(_ctx: &ScViewContext) -> FibonacciCall {
        let mut f = FibonacciCall {
            func: ScView::zero(),
            params: MutableFibonacciParams { id: 0 },
            results: ImmutableFibonacciResults { id: 0 },
        };
        f.func = ScView::new(HSC_NAME, HVIEW_FIBONACCI, &mut f.params.id, &mut f.results.id);
        f
    }
}

pub struct GetCounterCall {
    pub func: ScView,
    pub results: ImmutableGetCounterResults,
}

impl GetCounterCall {
    pub fn new(_ctx: &ScFuncContext) -> GetCounterCall {
        let mut f = GetCounterCall {
            func: ScView::zero(),
            results: ImmutableGetCounterResults { id: 0 },
        };
        f.func = ScView::new(HSC_NAME, HVIEW_GET_COUNTER, ptr::null_mut(), &mut f.results.id);
        f
    }

    pub fn new_from_view(_ctx: &ScViewContext) -> GetCounterCall {
        let mut f = GetCounterCall {
            func: ScView::zero(),
            results: ImmutableGetCounterResults { id: 0 },
        };
        f.func = ScView::new(HSC_NAME, HVIEW_GET_COUNTER, ptr::null_mut(), &mut f.results.id);
        f
    }
}

pub struct GetIntCall {
    pub func: ScView,
    pub params: MutableGetIntParams,
}

impl GetIntCall {
    pub fn new(_ctx: &ScFuncContext) -> GetIntCall {
        let mut f = GetIntCall {
            func: ScView::zero(),
            params: MutableGetIntParams { id: 0 },
        };
        f.func = ScView::new(HSC_NAME, HVIEW_GET_INT, &mut f.params.id, ptr::null_mut());
        f
    }

    pub fn new_from_view(_ctx: &ScViewContext) -> GetIntCall {
        let mut f = GetIntCall {
            func: ScView::zero(),
            params: MutableGetIntParams { id: 0 },
        };
        f.func = ScView::new(HSC_NAME, HVIEW_GET_INT, &mut f.params.id, ptr::null_mut());
        f
    }
}

pub struct JustViewCall {
    pub func: ScView,
}

impl JustViewCall {
    pub fn new(_ctx: &ScFuncContext) -> JustViewCall {
        let mut f = JustViewCall {
            func: ScView::zero(),
        };
        f.func = ScView::new(HSC_NAME, HVIEW_JUST_VIEW, ptr::null_mut(), ptr::null_mut());
        f
    }

    pub fn new_from_view(_ctx: &ScViewContext) -> JustViewCall {
        let mut f = JustViewCall {
            func: ScView::zero(),
        };
        f.func = ScView::new(HSC_NAME, HVIEW_JUST_VIEW, ptr::null_mut(), ptr::null_mut());
        f
    }
}

pub struct PassTypesViewCall {
    pub func: ScView,
    pub params: MutablePassTypesViewParams,
}

impl PassTypesViewCall {
    pub fn new(_ctx: &ScFuncContext) -> PassTypesViewCall {
        let mut f = PassTypesViewCall {
            func: ScView::zero(),
            params: MutablePassTypesViewParams { id: 0 },
        };
        f.func = ScView::new(HSC_NAME, HVIEW_PASS_TYPES_VIEW, &mut f.params.id, ptr::null_mut());
        f
    }

    pub fn new_from_view(_ctx: &ScViewContext) -> PassTypesViewCall {
        let mut f = PassTypesViewCall {
            func: ScView::zero(),
            params: MutablePassTypesViewParams { id: 0 },
        };
        f.func = ScView::new(HSC_NAME, HVIEW_PASS_TYPES_VIEW, &mut f.params.id, ptr::null_mut());
        f
    }
}

pub struct TestCallPanicViewEPFromViewCall {
    pub func: ScView,
}

impl TestCallPanicViewEPFromViewCall {
    pub fn new(_ctx: &ScFuncContext) -> TestCallPanicViewEPFromViewCall {
        let mut f = TestCallPanicViewEPFromViewCall {
            func: ScView::zero(),
        };
        f.func = ScView::new(HSC_NAME, HVIEW_TEST_CALL_PANIC_VIEW_EP_FROM_VIEW, ptr::null_mut(), ptr::null_mut());
        f
    }

    pub fn new_from_view(_ctx: &ScViewContext) -> TestCallPanicViewEPFromViewCall {
        let mut f = TestCallPanicViewEPFromViewCall {
            func: ScView::zero(),
        };
        f.func = ScView::new(HSC_NAME, HVIEW_TEST_CALL_PANIC_VIEW_EP_FROM_VIEW, ptr::null_mut(), ptr::null_mut());
        f
    }
}

pub struct TestChainOwnerIDViewCall {
    pub func: ScView,
    pub results: ImmutableTestChainOwnerIDViewResults,
}

impl TestChainOwnerIDViewCall {
    pub fn new(_ctx: &ScFuncContext) -> TestChainOwnerIDViewCall {
        let mut f = TestChainOwnerIDViewCall {
            func: ScView::zero(),
            results: ImmutableTestChainOwnerIDViewResults { id: 0 },
        };
        f.func = ScView::new(HSC_NAME, HVIEW_TEST_CHAIN_OWNER_ID_VIEW, ptr::null_mut(), &mut f.results.id);
        f
    }

    pub fn new_from_view(_ctx: &ScViewContext) -> TestChainOwnerIDViewCall {
        let mut f = TestChainOwnerIDViewCall {
            func: ScView::zero(),
            results: ImmutableTestChainOwnerIDViewResults { id: 0 },
        };
        f.func = ScView::new(HSC_NAME, HVIEW_TEST_CHAIN_OWNER_ID_VIEW, ptr::null_mut(), &mut f.results.id);
        f
    }
}

pub struct TestPanicViewEPCall {
    pub func: ScView,
}

impl TestPanicViewEPCall {
    pub fn new(_ctx: &ScFuncContext) -> TestPanicViewEPCall {
        let mut f = TestPanicViewEPCall {
            func: ScView::zero(),
        };
        f.func = ScView::new(HSC_NAME, HVIEW_TEST_PANIC_VIEW_EP, ptr::null_mut(), ptr::null_mut());
        f
    }

    pub fn new_from_view(_ctx: &ScViewContext) -> TestPanicViewEPCall {
        let mut f = TestPanicViewEPCall {
            func: ScView::zero(),
        };
        f.func = ScView::new(HSC_NAME, HVIEW_TEST_PANIC_VIEW_EP, ptr::null_mut(), ptr::null_mut());
        f
    }
}

pub struct TestSandboxCallCall {
    pub func: ScView,
    pub results: ImmutableTestSandboxCallResults,
}

impl TestSandboxCallCall {
    pub fn new(_ctx: &ScFuncContext) -> TestSandboxCallCall {
        let mut f = TestSandboxCallCall {
            func: ScView::zero(),
            results: ImmutableTestSandboxCallResults { id: 0 },
        };
        f.func = ScView::new(HSC_NAME, HVIEW_TEST_SANDBOX_CALL, ptr::null_mut(), &mut f.results.id);
        f
    }

    pub fn new_from_view(_ctx: &ScViewContext) -> TestSandboxCallCall {
        let mut f = TestSandboxCallCall {
            func: ScView::zero(),
            results: ImmutableTestSandboxCallResults { id: 0 },
        };
        f.func = ScView::new(HSC_NAME, HVIEW_TEST_SANDBOX_CALL, ptr::null_mut(), &mut f.results.id);
        f
    }
}
