// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

#![allow(dead_code)]

use wasmlib::*;

use crate::*;

pub const IDX_PARAM_ADDRESS: usize = 0;
pub const IDX_PARAM_AGENT_ID: usize = 1;
pub const IDX_PARAM_BYTES: usize = 2;
pub const IDX_PARAM_CHAIN_ID: usize = 3;
pub const IDX_PARAM_COLOR: usize = 4;
pub const IDX_PARAM_HASH: usize = 5;
pub const IDX_PARAM_HNAME: usize = 6;
pub const IDX_PARAM_INT64: usize = 7;
pub const IDX_PARAM_REQUEST_ID: usize = 8;
pub const IDX_PARAM_STRING: usize = 9;
pub const IDX_VAR_DUMMY: usize = 10;

pub const KEY_MAP_LEN: usize = 11;

pub const KEY_MAP: [&str; KEY_MAP_LEN] = [
    PARAM_ADDRESS,
    PARAM_AGENT_ID,
    PARAM_BYTES,
    PARAM_CHAIN_ID,
    PARAM_COLOR,
    PARAM_HASH,
    PARAM_HNAME,
    PARAM_INT64,
    PARAM_REQUEST_ID,
    PARAM_STRING,
    VAR_DUMMY,
];

pub static mut IDX_MAP: [Key32; KEY_MAP_LEN] = [Key32(0); KEY_MAP_LEN];

pub fn idx_map(idx: usize) -> Key32 {
    unsafe {
        IDX_MAP[idx]
    }
}
