// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

package org.iota.wasp.contracts.testcore.lib;

import org.iota.wasp.wasmlib.immutable.*;

//@formatter:off
public class FuncCheckContextFromFullEPParams {
    public ScImmutableAgentId   AgentId;
    public ScImmutableAgentId   Caller;
    public ScImmutableChainId   ChainId;
    public ScImmutableAgentId   ChainOwnerId;
    public ScImmutableAgentId   ContractCreator;
}
//@formatter:on
