// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

package org.iota.wasp.contracts.testcore.lib;

import de.mirkosertic.bytecoder.api.*;
import org.iota.wasp.contracts.testcore.*;
import org.iota.wasp.wasmlib.context.*;
import org.iota.wasp.wasmlib.exports.*;
import org.iota.wasp.wasmlib.immutable.*;

public class TestCoreThunk {
    public static void main(String[] args) {
    }

    @Export("on_load")
    public static void onLoad() {
        ScExports exports = new ScExports();
        exports.AddFunc("callOnChain", TestCoreThunk::funcCallOnChainThunk);
        exports.AddFunc("checkContextFromFullEP", TestCoreThunk::funcCheckContextFromFullEPThunk);
        exports.AddFunc("doNothing", TestCoreThunk::funcDoNothingThunk);
        exports.AddFunc("getMintedSupply", TestCoreThunk::funcGetMintedSupplyThunk);
        exports.AddFunc("incCounter", TestCoreThunk::funcIncCounterThunk);
        exports.AddFunc("init", TestCoreThunk::funcInitThunk);
        exports.AddFunc("passTypesFull", TestCoreThunk::funcPassTypesFullThunk);
        exports.AddFunc("runRecursion", TestCoreThunk::funcRunRecursionThunk);
        exports.AddFunc("sendToAddress", TestCoreThunk::funcSendToAddressThunk);
        exports.AddFunc("setInt", TestCoreThunk::funcSetIntThunk);
        exports.AddFunc("testCallPanicFullEP", TestCoreThunk::funcTestCallPanicFullEPThunk);
        exports.AddFunc("testCallPanicViewEPFromFull", TestCoreThunk::funcTestCallPanicViewEPFromFullThunk);
        exports.AddFunc("testChainOwnerIDFull", TestCoreThunk::funcTestChainOwnerIDFullThunk);
        exports.AddFunc("testContractIDFull", TestCoreThunk::funcTestContractIDFullThunk);
        exports.AddFunc("testEventLogDeploy", TestCoreThunk::funcTestEventLogDeployThunk);
        exports.AddFunc("testEventLogEventData", TestCoreThunk::funcTestEventLogEventDataThunk);
        exports.AddFunc("testEventLogGenericData", TestCoreThunk::funcTestEventLogGenericDataThunk);
        exports.AddFunc("testPanicFullEP", TestCoreThunk::funcTestPanicFullEPThunk);
        exports.AddFunc("withdrawToChain", TestCoreThunk::funcWithdrawToChainThunk);
        exports.AddView("checkContextFromViewEP", TestCoreThunk::viewCheckContextFromViewEPThunk);
        exports.AddView("fibonacci", TestCoreThunk::viewFibonacciThunk);
        exports.AddView("getCounter", TestCoreThunk::viewGetCounterThunk);
        exports.AddView("getInt", TestCoreThunk::viewGetIntThunk);
        exports.AddView("justView", TestCoreThunk::viewJustViewThunk);
        exports.AddView("passTypesView", TestCoreThunk::viewPassTypesViewThunk);
        exports.AddView("testCallPanicViewEPFromView", TestCoreThunk::viewTestCallPanicViewEPFromViewThunk);
        exports.AddView("testChainOwnerIDView", TestCoreThunk::viewTestChainOwnerIDViewThunk);
        exports.AddView("testContractIDView", TestCoreThunk::viewTestContractIDViewThunk);
        exports.AddView("testPanicViewEP", TestCoreThunk::viewTestPanicViewEPThunk);
        exports.AddView("testSandboxCall", TestCoreThunk::viewTestSandboxCallThunk);
    }

    private static void funcCallOnChainThunk(ScFuncContext ctx) {
        var p = ctx.Params();
        var params = new FuncCallOnChainParams();
        params.HnameContract = p.GetHname(Consts.ParamHnameContract);
        params.HnameEP = p.GetHname(Consts.ParamHnameEP);
        params.IntValue = p.GetInt64(Consts.ParamIntValue);
        ctx.Require(params.IntValue.Exists(), "missing mandatory intValue");
        ctx.Log("testcore.funcCallOnChain");
        TestCore.funcCallOnChain(ctx, params);
        ctx.Log("testcore.funcCallOnChain ok");
    }

    private static void funcCheckContextFromFullEPThunk(ScFuncContext ctx) {
        var p = ctx.Params();
        var params = new FuncCheckContextFromFullEPParams();
        params.AgentId = p.GetAgentId(Consts.ParamAgentId);
        params.Caller = p.GetAgentId(Consts.ParamCaller);
        params.ChainId = p.GetChainId(Consts.ParamChainId);
        params.ChainOwnerId = p.GetAgentId(Consts.ParamChainOwnerId);
        params.ContractCreator = p.GetAgentId(Consts.ParamContractCreator);
        params.ContractId = p.GetContractId(Consts.ParamContractId);
        ctx.Require(params.AgentId.Exists(), "missing mandatory agentId");
        ctx.Require(params.Caller.Exists(), "missing mandatory caller");
        ctx.Require(params.ChainId.Exists(), "missing mandatory chainId");
        ctx.Require(params.ChainOwnerId.Exists(), "missing mandatory chainOwnerId");
        ctx.Require(params.ContractCreator.Exists(), "missing mandatory contractCreator");
        ctx.Require(params.ContractId.Exists(), "missing mandatory contractId");
        ctx.Log("testcore.funcCheckContextFromFullEP");
        TestCore.funcCheckContextFromFullEP(ctx, params);
        ctx.Log("testcore.funcCheckContextFromFullEP ok");
    }

    private static void funcDoNothingThunk(ScFuncContext ctx) {
        var params = new FuncDoNothingParams();
        ctx.Log("testcore.funcDoNothing");
        TestCore.funcDoNothing(ctx, params);
        ctx.Log("testcore.funcDoNothing ok");
    }

    private static void funcGetMintedSupplyThunk(ScFuncContext ctx) {
        var params = new FuncGetMintedSupplyParams();
        ctx.Log("testcore.funcGetMintedSupply");
        TestCore.funcGetMintedSupply(ctx, params);
        ctx.Log("testcore.funcGetMintedSupply ok");
    }

    private static void funcIncCounterThunk(ScFuncContext ctx) {
        var params = new FuncIncCounterParams();
        ctx.Log("testcore.funcIncCounter");
        TestCore.funcIncCounter(ctx, params);
        ctx.Log("testcore.funcIncCounter ok");
    }

    private static void funcInitThunk(ScFuncContext ctx) {
        var params = new FuncInitParams();
        ctx.Log("testcore.funcInit");
        TestCore.funcInit(ctx, params);
        ctx.Log("testcore.funcInit ok");
    }

    private static void funcPassTypesFullThunk(ScFuncContext ctx) {
        var p = ctx.Params();
        var params = new FuncPassTypesFullParams();
        params.Hash = p.GetHash(Consts.ParamHash);
        params.Hname = p.GetHname(Consts.ParamHname);
        params.HnameZero = p.GetHname(Consts.ParamHnameZero);
        params.Int64 = p.GetInt64(Consts.ParamInt64);
        params.Int64Zero = p.GetInt64(Consts.ParamInt64Zero);
        params.String = p.GetString(Consts.ParamString);
        params.StringZero = p.GetString(Consts.ParamStringZero);
        ctx.Require(params.Hash.Exists(), "missing mandatory hash");
        ctx.Require(params.Hname.Exists(), "missing mandatory hname");
        ctx.Require(params.HnameZero.Exists(), "missing mandatory hnameZero");
        ctx.Require(params.Int64.Exists(), "missing mandatory int64");
        ctx.Require(params.Int64Zero.Exists(), "missing mandatory int64Zero");
        ctx.Require(params.String.Exists(), "missing mandatory string");
        ctx.Require(params.StringZero.Exists(), "missing mandatory stringZero");
        ctx.Log("testcore.funcPassTypesFull");
        TestCore.funcPassTypesFull(ctx, params);
        ctx.Log("testcore.funcPassTypesFull ok");
    }

    private static void funcRunRecursionThunk(ScFuncContext ctx) {
        var p = ctx.Params();
        var params = new FuncRunRecursionParams();
        params.IntValue = p.GetInt64(Consts.ParamIntValue);
        ctx.Require(params.IntValue.Exists(), "missing mandatory intValue");
        ctx.Log("testcore.funcRunRecursion");
        TestCore.funcRunRecursion(ctx, params);
        ctx.Log("testcore.funcRunRecursion ok");
    }

    private static void funcSendToAddressThunk(ScFuncContext ctx) {
        ctx.Require(ctx.Caller().equals(ctx.ContractCreator()), "no permission");

        var p = ctx.Params();
        var params = new FuncSendToAddressParams();
        params.Address = p.GetAddress(Consts.ParamAddress);
        ctx.Require(params.Address.Exists(), "missing mandatory address");
        ctx.Log("testcore.funcSendToAddress");
        TestCore.funcSendToAddress(ctx, params);
        ctx.Log("testcore.funcSendToAddress ok");
    }

    private static void funcSetIntThunk(ScFuncContext ctx) {
        var p = ctx.Params();
        var params = new FuncSetIntParams();
        params.IntValue = p.GetInt64(Consts.ParamIntValue);
        params.Name = p.GetString(Consts.ParamName);
        ctx.Require(params.IntValue.Exists(), "missing mandatory intValue");
        ctx.Require(params.Name.Exists(), "missing mandatory name");
        ctx.Log("testcore.funcSetInt");
        TestCore.funcSetInt(ctx, params);
        ctx.Log("testcore.funcSetInt ok");
    }

    private static void funcTestCallPanicFullEPThunk(ScFuncContext ctx) {
        var params = new FuncTestCallPanicFullEPParams();
        ctx.Log("testcore.funcTestCallPanicFullEP");
        TestCore.funcTestCallPanicFullEP(ctx, params);
        ctx.Log("testcore.funcTestCallPanicFullEP ok");
    }

    private static void funcTestCallPanicViewEPFromFullThunk(ScFuncContext ctx) {
        var params = new FuncTestCallPanicViewEPFromFullParams();
        ctx.Log("testcore.funcTestCallPanicViewEPFromFull");
        TestCore.funcTestCallPanicViewEPFromFull(ctx, params);
        ctx.Log("testcore.funcTestCallPanicViewEPFromFull ok");
    }

    private static void funcTestChainOwnerIDFullThunk(ScFuncContext ctx) {
        var params = new FuncTestChainOwnerIDFullParams();
        ctx.Log("testcore.funcTestChainOwnerIDFull");
        TestCore.funcTestChainOwnerIDFull(ctx, params);
        ctx.Log("testcore.funcTestChainOwnerIDFull ok");
    }

    private static void funcTestContractIDFullThunk(ScFuncContext ctx) {
        var params = new FuncTestContractIDFullParams();
        ctx.Log("testcore.funcTestContractIDFull");
        TestCore.funcTestContractIDFull(ctx, params);
        ctx.Log("testcore.funcTestContractIDFull ok");
    }

    private static void funcTestEventLogDeployThunk(ScFuncContext ctx) {
        var params = new FuncTestEventLogDeployParams();
        ctx.Log("testcore.funcTestEventLogDeploy");
        TestCore.funcTestEventLogDeploy(ctx, params);
        ctx.Log("testcore.funcTestEventLogDeploy ok");
    }

    private static void funcTestEventLogEventDataThunk(ScFuncContext ctx) {
        var params = new FuncTestEventLogEventDataParams();
        ctx.Log("testcore.funcTestEventLogEventData");
        TestCore.funcTestEventLogEventData(ctx, params);
        ctx.Log("testcore.funcTestEventLogEventData ok");
    }

    private static void funcTestEventLogGenericDataThunk(ScFuncContext ctx) {
        var p = ctx.Params();
        var params = new FuncTestEventLogGenericDataParams();
        params.Counter = p.GetInt64(Consts.ParamCounter);
        ctx.Require(params.Counter.Exists(), "missing mandatory counter");
        ctx.Log("testcore.funcTestEventLogGenericData");
        TestCore.funcTestEventLogGenericData(ctx, params);
        ctx.Log("testcore.funcTestEventLogGenericData ok");
    }

    private static void funcTestPanicFullEPThunk(ScFuncContext ctx) {
        var params = new FuncTestPanicFullEPParams();
        ctx.Log("testcore.funcTestPanicFullEP");
        TestCore.funcTestPanicFullEP(ctx, params);
        ctx.Log("testcore.funcTestPanicFullEP ok");
    }

    private static void funcWithdrawToChainThunk(ScFuncContext ctx) {
        var p = ctx.Params();
        var params = new FuncWithdrawToChainParams();
        params.ChainId = p.GetChainId(Consts.ParamChainId);
        ctx.Require(params.ChainId.Exists(), "missing mandatory chainId");
        ctx.Log("testcore.funcWithdrawToChain");
        TestCore.funcWithdrawToChain(ctx, params);
        ctx.Log("testcore.funcWithdrawToChain ok");
    }

    private static void viewCheckContextFromViewEPThunk(ScViewContext ctx) {
        var p = ctx.Params();
        var params = new ViewCheckContextFromViewEPParams();
        params.AgentId = p.GetAgentId(Consts.ParamAgentId);
        params.ChainId = p.GetChainId(Consts.ParamChainId);
        params.ChainOwnerId = p.GetAgentId(Consts.ParamChainOwnerId);
        params.ContractCreator = p.GetAgentId(Consts.ParamContractCreator);
        params.ContractId = p.GetContractId(Consts.ParamContractId);
        ctx.Require(params.AgentId.Exists(), "missing mandatory agentId");
        ctx.Require(params.ChainId.Exists(), "missing mandatory chainId");
        ctx.Require(params.ChainOwnerId.Exists(), "missing mandatory chainOwnerId");
        ctx.Require(params.ContractCreator.Exists(), "missing mandatory contractCreator");
        ctx.Require(params.ContractId.Exists(), "missing mandatory contractId");
        ctx.Log("testcore.viewCheckContextFromViewEP");
        TestCore.viewCheckContextFromViewEP(ctx, params);
        ctx.Log("testcore.viewCheckContextFromViewEP ok");
    }

    private static void viewFibonacciThunk(ScViewContext ctx) {
        var p = ctx.Params();
        var params = new ViewFibonacciParams();
        params.IntValue = p.GetInt64(Consts.ParamIntValue);
        ctx.Require(params.IntValue.Exists(), "missing mandatory intValue");
        ctx.Log("testcore.viewFibonacci");
        TestCore.viewFibonacci(ctx, params);
        ctx.Log("testcore.viewFibonacci ok");
    }

    private static void viewGetCounterThunk(ScViewContext ctx) {
        var params = new ViewGetCounterParams();
        ctx.Log("testcore.viewGetCounter");
        TestCore.viewGetCounter(ctx, params);
        ctx.Log("testcore.viewGetCounter ok");
    }

    private static void viewGetIntThunk(ScViewContext ctx) {
        var p = ctx.Params();
        var params = new ViewGetIntParams();
        params.Name = p.GetString(Consts.ParamName);
        ctx.Require(params.Name.Exists(), "missing mandatory name");
        ctx.Log("testcore.viewGetInt");
        TestCore.viewGetInt(ctx, params);
        ctx.Log("testcore.viewGetInt ok");
    }

    private static void viewJustViewThunk(ScViewContext ctx) {
        var params = new ViewJustViewParams();
        ctx.Log("testcore.viewJustView");
        TestCore.viewJustView(ctx, params);
        ctx.Log("testcore.viewJustView ok");
    }

    private static void viewPassTypesViewThunk(ScViewContext ctx) {
        var p = ctx.Params();
        var params = new ViewPassTypesViewParams();
        params.Hash = p.GetHash(Consts.ParamHash);
        params.Hname = p.GetHname(Consts.ParamHname);
        params.HnameZero = p.GetHname(Consts.ParamHnameZero);
        params.Int64 = p.GetInt64(Consts.ParamInt64);
        params.Int64Zero = p.GetInt64(Consts.ParamInt64Zero);
        params.String = p.GetString(Consts.ParamString);
        params.StringZero = p.GetString(Consts.ParamStringZero);
        ctx.Require(params.Hash.Exists(), "missing mandatory hash");
        ctx.Require(params.Hname.Exists(), "missing mandatory hname");
        ctx.Require(params.HnameZero.Exists(), "missing mandatory hnameZero");
        ctx.Require(params.Int64.Exists(), "missing mandatory int64");
        ctx.Require(params.Int64Zero.Exists(), "missing mandatory int64Zero");
        ctx.Require(params.String.Exists(), "missing mandatory string");
        ctx.Require(params.StringZero.Exists(), "missing mandatory stringZero");
        ctx.Log("testcore.viewPassTypesView");
        TestCore.viewPassTypesView(ctx, params);
        ctx.Log("testcore.viewPassTypesView ok");
    }

    private static void viewTestCallPanicViewEPFromViewThunk(ScViewContext ctx) {
        var params = new ViewTestCallPanicViewEPFromViewParams();
        ctx.Log("testcore.viewTestCallPanicViewEPFromView");
        TestCore.viewTestCallPanicViewEPFromView(ctx, params);
        ctx.Log("testcore.viewTestCallPanicViewEPFromView ok");
    }

    private static void viewTestChainOwnerIDViewThunk(ScViewContext ctx) {
        var params = new ViewTestChainOwnerIDViewParams();
        ctx.Log("testcore.viewTestChainOwnerIDView");
        TestCore.viewTestChainOwnerIDView(ctx, params);
        ctx.Log("testcore.viewTestChainOwnerIDView ok");
    }

    private static void viewTestContractIDViewThunk(ScViewContext ctx) {
        var params = new ViewTestContractIDViewParams();
        ctx.Log("testcore.viewTestContractIDView");
        TestCore.viewTestContractIDView(ctx, params);
        ctx.Log("testcore.viewTestContractIDView ok");
    }

    private static void viewTestPanicViewEPThunk(ScViewContext ctx) {
        var params = new ViewTestPanicViewEPParams();
        ctx.Log("testcore.viewTestPanicViewEP");
        TestCore.viewTestPanicViewEP(ctx, params);
        ctx.Log("testcore.viewTestPanicViewEP ok");
    }

    private static void viewTestSandboxCallThunk(ScViewContext ctx) {
        var params = new ViewTestSandboxCallParams();
        ctx.Log("testcore.viewTestSandboxCall");
        TestCore.viewTestSandboxCall(ctx, params);
        ctx.Log("testcore.viewTestSandboxCall ok");
    }
}
