// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

package org.iota.wasp.contracts.inccounter.lib;

import org.iota.wasp.wasmlib.hashtypes.*;
import org.iota.wasp.wasmlib.keys.*;

public class Consts {
    public static final String ScName = "inccounter";
    public static final ScHname HScName = new ScHname(0xaf2438e9);

    public static final Key ParamCounter = new Key("counter");
    public static final Key ParamNumRepeats = new Key("numRepeats");

    public static final Key VarCounter = new Key("counter");
    public static final Key VarInt1 = new Key("int1");
    public static final Key VarIntArray1 = new Key("intArray1");
    public static final Key VarNumRepeats = new Key("numRepeats");
    public static final Key VarString1 = new Key("string1");
    public static final Key VarStringArray1 = new Key("stringArray1");

    public static final String FuncCallIncrement = "callIncrement";
    public static final String FuncCallIncrementRecurse5x = "callIncrementRecurse5x";
    public static final String FuncIncrement = "increment";
    public static final String FuncInit = "init";
    public static final String FuncLocalStateInternalCall = "localStateInternalCall";
    public static final String FuncLocalStatePost = "localStatePost";
    public static final String FuncLocalStateSandboxCall = "localStateSandboxCall";
    public static final String FuncPostIncrement = "postIncrement";
    public static final String FuncRepeatMany = "repeatMany";
    public static final String FuncWhenMustIncrement = "whenMustIncrement";
    public static final String ViewGetCounter = "getCounter";

    public static final ScHname HFuncCallIncrement = new ScHname(0xeb5dcacd);
    public static final ScHname HFuncCallIncrementRecurse5x = new ScHname(0x8749fbff);
    public static final ScHname HFuncIncrement = new ScHname(0xd351bd12);
    public static final ScHname HFuncInit = new ScHname(0x1f44d644);
    public static final ScHname HFuncLocalStateInternalCall = new ScHname(0xecfc5d33);
    public static final ScHname HFuncLocalStatePost = new ScHname(0x3fd54d13);
    public static final ScHname HFuncLocalStateSandboxCall = new ScHname(0x7bd22c53);
    public static final ScHname HFuncPostIncrement = new ScHname(0x81c772f5);
    public static final ScHname HFuncRepeatMany = new ScHname(0x4ff450d3);
    public static final ScHname HFuncWhenMustIncrement = new ScHname(0xb4c3e7a6);
    public static final ScHname HViewGetCounter = new ScHname(0xb423e607);
}
