// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

package org.iota.wasp.contracts.tokenregistry.lib;

import org.iota.wasp.wasmlib.immutable.*;

public class FuncMintSupplyParams {
	public ScImmutableString Description; // description what minted token represents
	public ScImmutableString UserDefined; // any user defined text
}
