// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

package dividend

import "github.com/iotaledger/wasplib/packages/vm/wasmlib"

func OnLoad() {
	exports := wasmlib.NewScExports()
	exports.AddFunc(FuncDivide, funcDivideThunk)
	exports.AddFunc(FuncInit, funcInitThunk)
	exports.AddFunc(FuncMember, funcMemberThunk)
	exports.AddFunc(FuncSetOwner, funcSetOwnerThunk)
	exports.AddView(ViewGetFactor, viewGetFactorThunk)
}

type FuncDivideParams struct {
}

func funcDivideThunk(ctx wasmlib.ScFuncContext) {
	ctx.Log("dividend.funcDivide")
	params := &FuncDivideParams{
	}
	funcDivide(ctx, params)
	ctx.Log("dividend.funcDivide ok")
}

type FuncInitParams struct {
	Owner wasmlib.ScImmutableAgentId // optional owner, defaults to contract creator
}

func funcInitThunk(ctx wasmlib.ScFuncContext) {
	ctx.Log("dividend.funcInit")
	p := ctx.Params()
	params := &FuncInitParams{
		Owner: p.GetAgentId(ParamOwner),
	}
	funcInit(ctx, params)
	ctx.Log("dividend.funcInit ok")
}

type FuncMemberParams struct {
	Address wasmlib.ScImmutableAddress // address of dividend recipient
	Factor  wasmlib.ScImmutableInt64   // relative division factor
}

func funcMemberThunk(ctx wasmlib.ScFuncContext) {
	ctx.Log("dividend.funcMember")
	// only defined owner can add members
	grantee := ctx.State().GetAgentId(wasmlib.Key("owner"))
	ctx.Require(grantee.Exists(), "grantee not set: owner")
	ctx.Require(ctx.Caller() == grantee.Value(), "no permission")

	p := ctx.Params()
	params := &FuncMemberParams{
		Address: p.GetAddress(ParamAddress),
		Factor:  p.GetInt64(ParamFactor),
	}
	ctx.Require(params.Address.Exists(), "missing mandatory address")
	ctx.Require(params.Factor.Exists(), "missing mandatory factor")
	funcMember(ctx, params)
	ctx.Log("dividend.funcMember ok")
}

type FuncSetOwnerParams struct {
	Owner wasmlib.ScImmutableAgentId // new owner of smart contract
}

func funcSetOwnerThunk(ctx wasmlib.ScFuncContext) {
	ctx.Log("dividend.funcSetOwner")
	// only defined owner can change owner
	grantee := ctx.State().GetAgentId(wasmlib.Key("owner"))
	ctx.Require(grantee.Exists(), "grantee not set: owner")
	ctx.Require(ctx.Caller() == grantee.Value(), "no permission")

	p := ctx.Params()
	params := &FuncSetOwnerParams{
		Owner: p.GetAgentId(ParamOwner),
	}
	ctx.Require(params.Owner.Exists(), "missing mandatory owner")
	funcSetOwner(ctx, params)
	ctx.Log("dividend.funcSetOwner ok")
}

type ViewGetFactorParams struct {
	Address wasmlib.ScImmutableAddress // address of dividend recipient
}

func viewGetFactorThunk(ctx wasmlib.ScViewContext) {
	ctx.Log("dividend.viewGetFactor")
	p := ctx.Params()
	params := &ViewGetFactorParams{
		Address: p.GetAddress(ParamAddress),
	}
	ctx.Require(params.Address.Exists(), "missing mandatory address")
	viewGetFactor(ctx, params)
	ctx.Log("dividend.viewGetFactor ok")
}
