// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

package coreblob

import "github.com/iotaledger/wasplib/packages/vm/wasmlib"

type StoreBlobCall struct {
	Func wasmlib.ScFunc
	Results ImmutableStoreBlobResults
}

func NewStoreBlobCall(ctx wasmlib.ScFuncContext) *StoreBlobCall {
	f := &StoreBlobCall{}
	f.Func.Init(HScName, HFuncStoreBlob, nil, &f.Results.id)
	return f
}

type GetBlobFieldCall struct {
	Func wasmlib.ScView
	Params MutableGetBlobFieldParams
	Results ImmutableGetBlobFieldResults
}

func NewGetBlobFieldCall(ctx wasmlib.ScFuncContext) *GetBlobFieldCall {
	f := &GetBlobFieldCall{}
	f.Func.Init(HScName, HViewGetBlobField, &f.Params.id, &f.Results.id)
	return f
}

func NewGetBlobFieldCallFromView(ctx wasmlib.ScViewContext) *GetBlobFieldCall {
	f := &GetBlobFieldCall{}
	f.Func.Init(HScName, HViewGetBlobField, &f.Params.id, &f.Results.id)
	return f
}

type GetBlobInfoCall struct {
	Func wasmlib.ScView
	Params MutableGetBlobInfoParams
}

func NewGetBlobInfoCall(ctx wasmlib.ScFuncContext) *GetBlobInfoCall {
	f := &GetBlobInfoCall{}
	f.Func.Init(HScName, HViewGetBlobInfo, &f.Params.id, nil)
	return f
}

func NewGetBlobInfoCallFromView(ctx wasmlib.ScViewContext) *GetBlobInfoCall {
	f := &GetBlobInfoCall{}
	f.Func.Init(HScName, HViewGetBlobInfo, &f.Params.id, nil)
	return f
}

type ListBlobsCall struct {
	Func wasmlib.ScView
}

func NewListBlobsCall(ctx wasmlib.ScFuncContext) *ListBlobsCall {
	f := &ListBlobsCall{}
	f.Func.Init(HScName, HViewListBlobs, nil, nil)
	return f
}

func NewListBlobsCallFromView(ctx wasmlib.ScViewContext) *ListBlobsCall {
	f := &ListBlobsCall{}
	f.Func.Init(HScName, HViewListBlobs, nil, nil)
	return f
}
