// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

package coreblob

import "github.com/iotaledger/wasplib/packages/vm/wasmlib"

type ImmutableGetBlobFieldParams struct {
	id int32
}

func (s ImmutableGetBlobFieldParams) Field() wasmlib.ScImmutableString {
	return wasmlib.NewScImmutableString(s.id, ParamField.KeyId())
}

func (s ImmutableGetBlobFieldParams) Hash() wasmlib.ScImmutableHash {
	return wasmlib.NewScImmutableHash(s.id, ParamHash.KeyId())
}

type MutableGetBlobFieldParams struct {
	id int32
}

func (s MutableGetBlobFieldParams) Field() wasmlib.ScMutableString {
	return wasmlib.NewScMutableString(s.id, ParamField.KeyId())
}

func (s MutableGetBlobFieldParams) Hash() wasmlib.ScMutableHash {
	return wasmlib.NewScMutableHash(s.id, ParamHash.KeyId())
}

type ImmutableGetBlobInfoParams struct {
	id int32
}

func (s ImmutableGetBlobInfoParams) Hash() wasmlib.ScImmutableHash {
	return wasmlib.NewScImmutableHash(s.id, ParamHash.KeyId())
}

type MutableGetBlobInfoParams struct {
	id int32
}

func (s MutableGetBlobInfoParams) Hash() wasmlib.ScMutableHash {
	return wasmlib.NewScMutableHash(s.id, ParamHash.KeyId())
}
