// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

package donatewithfeedback

import "github.com/iotaledger/wasplib/packages/vm/wasmlib"

const ScName = "donatewithfeedback"
const HScName = wasmlib.ScHname(0x696d7f66)

const ParamAmount = wasmlib.Key("amount")
const ParamFeedback = wasmlib.Key("feedback")
const ParamNr = wasmlib.Key("nr")

const ResultAmount = wasmlib.Key("amount")
const ResultCount = wasmlib.Key("count")
const ResultDonator = wasmlib.Key("donator")
const ResultError = wasmlib.Key("error")
const ResultFeedback = wasmlib.Key("feedback")
const ResultMaxDonation = wasmlib.Key("maxDonation")
const ResultTimestamp = wasmlib.Key("timestamp")
const ResultTotalDonation = wasmlib.Key("totalDonation")

const VarLog = wasmlib.Key("log")
const VarMaxDonation = wasmlib.Key("maxDonation")
const VarTotalDonation = wasmlib.Key("totalDonation")

const FuncDonate = "donate"
const FuncWithdraw = "withdraw"
const ViewDonation = "donation"
const ViewDonationInfo = "donationInfo"

const HFuncDonate = wasmlib.ScHname(0xdc9b133a)
const HFuncWithdraw = wasmlib.ScHname(0x9dcc0f41)
const HViewDonation = wasmlib.ScHname(0xbdb245ba)
const HViewDonationInfo = wasmlib.ScHname(0xc8f7c726)
