// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

package testwasmlib

import "github.com/iotaledger/wasplib/packages/vm/wasmlib"

const ScName = "testwasmlib"
const ScDescription = "Exercise all aspects of WasmLib"
const HScName = wasmlib.ScHname(0x89703a45)

const ParamAddress = "address"
const ParamAgentId = "agentId"
const ParamBytes = "bytes"
const ParamChainId = "chainId"
const ParamColor = "color"
const ParamHash = "hash"
const ParamHname = "hname"
const ParamInt64 = "int64"
const ParamRequestId = "requestId"
const ParamString = "string"

const VarDummy = "dummy"

const FuncParamTypes = "paramTypes"

const HFuncParamTypes = wasmlib.ScHname(0x6921c4cd)
