// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

package testwasmlib

import "github.com/iotaledger/wasplib/packages/vm/wasmlib"

const IdxParamAddress = 0
const IdxParamAgentId = 1
const IdxParamBytes = 2
const IdxParamChainId = 3
const IdxParamColor = 4
const IdxParamHash = 5
const IdxParamHname = 6
const IdxParamInt64 = 7
const IdxParamRequestId = 8
const IdxParamString = 9

var keyMap = [10]wasmlib.Key{
	ParamAddress,
	ParamAgentId,
	ParamBytes,
	ParamChainId,
	ParamColor,
	ParamHash,
	ParamHname,
	ParamInt64,
	ParamRequestId,
	ParamString,
}

var idxMap [10]wasmlib.Key32
