// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

//@formatter:off

#![allow(dead_code)]

#![allow(unused_imports)]

use donatewithfeedback::*;
use wasmlib::*;
use wasmlib::host::*;

use crate::consts::*;
use crate::keys::*;
use crate::params::*;
use crate::results::*;
use crate::state::*;

mod consts;
mod contract;
mod keys;
mod params;
mod results;
mod state;
mod types;
mod donatewithfeedback;

#[no_mangle]
fn on_load() {
    let exports = ScExports::new();
    exports.add_func(FUNC_DONATE, func_donate_thunk);
    exports.add_func(FUNC_WITHDRAW, func_withdraw_thunk);
    exports.add_view(VIEW_DONATION, view_donation_thunk);
    exports.add_view(VIEW_DONATION_INFO, view_donation_info_thunk);

    unsafe {
        for i in 0..KEY_MAP_LEN {
            IDX_MAP[i] = get_key_id_from_string(KEY_MAP[i]);
        }
    }
}

pub struct FuncDonateContext {
    params: ImmutableFuncDonateParams,
    state:  MutableDonateWithFeedbackState,
}

fn func_donate_thunk(ctx: &ScFuncContext) {
    ctx.log("donatewithfeedback.funcDonate");
    let f = FuncDonateContext {
        params: ImmutableFuncDonateParams {
            id: get_object_id(1, KEY_PARAMS, TYPE_MAP),
        },
        state: MutableDonateWithFeedbackState {
            id: get_object_id(1, KEY_STATE, TYPE_MAP),
        },
    };
    func_donate(ctx, &f);
    ctx.log("donatewithfeedback.funcDonate ok");
}

pub struct FuncWithdrawContext {
    params: ImmutableFuncWithdrawParams,
    state:  MutableDonateWithFeedbackState,
}

fn func_withdraw_thunk(ctx: &ScFuncContext) {
    ctx.log("donatewithfeedback.funcWithdraw");
    // only SC creator can withdraw donated funds
    ctx.require(ctx.caller() == ctx.contract_creator(), "no permission");

    let f = FuncWithdrawContext {
        params: ImmutableFuncWithdrawParams {
            id: get_object_id(1, KEY_PARAMS, TYPE_MAP),
        },
        state: MutableDonateWithFeedbackState {
            id: get_object_id(1, KEY_STATE, TYPE_MAP),
        },
    };
    func_withdraw(ctx, &f);
    ctx.log("donatewithfeedback.funcWithdraw ok");
}

pub struct ViewDonationContext {
    params:  ImmutableViewDonationParams,
    results: MutableViewDonationResults,
    state:   ImmutableDonateWithFeedbackState,
}

fn view_donation_thunk(ctx: &ScViewContext) {
    ctx.log("donatewithfeedback.viewDonation");
    let f = ViewDonationContext {
        params: ImmutableViewDonationParams {
            id: get_object_id(1, KEY_PARAMS, TYPE_MAP),
        },
        results: MutableViewDonationResults {
            id: get_object_id(1, KEY_RESULTS, TYPE_MAP),
        },
        state: ImmutableDonateWithFeedbackState {
            id: get_object_id(1, KEY_STATE, TYPE_MAP),
        },
    };
    ctx.require(f.params.nr().exists(), "missing mandatory nr");
    view_donation(ctx, &f);
    ctx.log("donatewithfeedback.viewDonation ok");
}

pub struct ViewDonationInfoContext {
    results: MutableViewDonationInfoResults,
    state:   ImmutableDonateWithFeedbackState,
}

fn view_donation_info_thunk(ctx: &ScViewContext) {
    ctx.log("donatewithfeedback.viewDonationInfo");
    let f = ViewDonationInfoContext {
        results: MutableViewDonationInfoResults {
            id: get_object_id(1, KEY_RESULTS, TYPE_MAP),
        },
        state: ImmutableDonateWithFeedbackState {
            id: get_object_id(1, KEY_STATE, TYPE_MAP),
        },
    };
    view_donation_info(ctx, &f);
    ctx.log("donatewithfeedback.viewDonationInfo ok");
}

//@formatter:on
