// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

#![allow(dead_code)]

use wasmlib::*;

//@formatter:off
pub struct BetInfo {
    pub amount: i64,      
    pub better: ScAgentId,
    pub number: i64,      
}
//@formatter:on

pub fn encode_bet_info(o: &BetInfo) -> Vec<u8> {
    let mut encode = BytesEncoder::new();
    encode.int(o.amount);
    encode.agent_id(&o.better);
    encode.int(o.number);
    return encode.data();
}

pub fn decode_bet_info(bytes: &[u8]) -> BetInfo {
    let mut decode = BytesDecoder::new(bytes);
    BetInfo {
        amount: decode.int(),
        better: decode.agent_id(),
        number: decode.int(),
    }
}
