// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead


package org.iota.wasp.contracts.erc20.lib;

import org.iota.wasp.contracts.erc20.*;
import org.iota.wasp.wasmlib.exports.*;
import org.iota.wasp.wasmlib.hashtypes.*;

public class Erc20Thunk {
	public static void onLoad() {
		ScExports exports = new ScExports();
		exports.AddFunc("approve", Erc20::FuncApprove);
		exports.AddFunc("init", Erc20::FuncInit);
		exports.AddFunc("transfer", Erc20::FuncTransfer);
		exports.AddFunc("transferFrom", Erc20::FuncTransferFrom);
		exports.AddView("allowance", Erc20::ViewAllowance);
		exports.AddView("balanceOf", Erc20::ViewBalanceOf);
		exports.AddView("totalSupply", Erc20::ViewTotalSupply);
	}
}
