// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package betting

import "github.com/iotaledger/wasplib/packages/vm/wasmlib"

const (
	IdxParamOwner  = 0
	IdxResultOwner = 1
	IdxStateOwner  = 2
	IdxStateRounds = 3
)

const keyMapLen = 4

var keyMap = [keyMapLen]wasmlib.Key{
	ParamOwner,
	ResultOwner,
	StateOwner,
	StateRounds,
}

var idxMap [keyMapLen]wasmlib.Key32
