// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

package coregovernance

import "github.com/iotaledger/wasplib/packages/vm/wasmlib"

type ImmutableFuncAddAllowedStateControllerAddressParams struct {
	id int32
}

func (s ImmutableFuncAddAllowedStateControllerAddressParams) StateControllerAddress() wasmlib.ScImmutableAddress {
	return wasmlib.NewScImmutableAddress(s.id, ParamStateControllerAddress.KeyId())
}

type MutableFuncAddAllowedStateControllerAddressParams struct {
	id int32
}

func NewMutableFuncAddAllowedStateControllerAddressParams() MutableFuncAddAllowedStateControllerAddressParams {
	return MutableFuncAddAllowedStateControllerAddressParams{id: wasmlib.NewScMutableMap().MapId()}
}

func (s MutableFuncAddAllowedStateControllerAddressParams) StateControllerAddress() wasmlib.ScMutableAddress {
	return wasmlib.NewScMutableAddress(s.id, ParamStateControllerAddress.KeyId())
}

type ImmutableFuncRemoveAllowedStateControllerAddressParams struct {
	id int32
}

func (s ImmutableFuncRemoveAllowedStateControllerAddressParams) StateControllerAddress() wasmlib.ScImmutableAddress {
	return wasmlib.NewScImmutableAddress(s.id, ParamStateControllerAddress.KeyId())
}

type MutableFuncRemoveAllowedStateControllerAddressParams struct {
	id int32
}

func NewMutableFuncRemoveAllowedStateControllerAddressParams() MutableFuncRemoveAllowedStateControllerAddressParams {
	return MutableFuncRemoveAllowedStateControllerAddressParams{id: wasmlib.NewScMutableMap().MapId()}
}

func (s MutableFuncRemoveAllowedStateControllerAddressParams) StateControllerAddress() wasmlib.ScMutableAddress {
	return wasmlib.NewScMutableAddress(s.id, ParamStateControllerAddress.KeyId())
}

type ImmutableFuncRotateStateControllerParams struct {
	id int32
}

func (s ImmutableFuncRotateStateControllerParams) StateControllerAddress() wasmlib.ScImmutableAddress {
	return wasmlib.NewScImmutableAddress(s.id, ParamStateControllerAddress.KeyId())
}

type MutableFuncRotateStateControllerParams struct {
	id int32
}

func NewMutableFuncRotateStateControllerParams() MutableFuncRotateStateControllerParams {
	return MutableFuncRotateStateControllerParams{id: wasmlib.NewScMutableMap().MapId()}
}

func (s MutableFuncRotateStateControllerParams) StateControllerAddress() wasmlib.ScMutableAddress {
	return wasmlib.NewScMutableAddress(s.id, ParamStateControllerAddress.KeyId())
}
