// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

package org.iota.wasp.contracts.dividend.lib;

import de.mirkosertic.bytecoder.api.*;
import org.iota.wasp.contracts.dividend.*;
import org.iota.wasp.wasmlib.context.*;
import org.iota.wasp.wasmlib.exports.*;
import org.iota.wasp.wasmlib.immutable.*;
import org.iota.wasp.wasmlib.keys.*;

public class DividendThunk {
    public static void main(String[] args) {
    }

    @Export("on_load")
    public static void onLoad() {
        ScExports exports = new ScExports();
        exports.AddFunc(Consts.FuncDivide, DividendThunk::funcDivideThunk);
        exports.AddFunc(Consts.FuncInit, DividendThunk::funcInitThunk);
        exports.AddFunc(Consts.FuncMember, DividendThunk::funcMemberThunk);
        exports.AddFunc(Consts.FuncSetOwner, DividendThunk::funcSetOwnerThunk);
        exports.AddView(Consts.ViewGetFactor, DividendThunk::viewGetFactorThunk);
    }

    private static void funcDivideThunk(ScFuncContext ctx) {
        ctx.Log("dividend.funcDivide");
        var params = new FuncDivideParams();
        Dividend.funcDivide(ctx, params);
        ctx.Log("dividend.funcDivide ok");
    }
