// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

package aaa

import "github.com/iotaledger/wasp/packages/vm/wasmlib"

func OnLoad() {
    exports := wasmlib.NewScExports()
    exports.AddFunc(FuncMyFunc, funcMyFuncThunk)
    exports.AddView(ViewMyView, viewMyViewThunk)
}

type FuncMyFuncParams struct {
    Text wasmlib.ScImmutableString // some mandatory string parameter
}

func funcMyFuncThunk(ctx *wasmlib.ScFuncContext) {
    p := ctx.Params()
    params := &FuncMyFuncParams {
        Text: p.GetString(ParamText),
    }
    ctx.Require(params.Text.Exists(), "missing mandatory text")
    funcMyFunc(ctx, params)
}

type ViewMyViewParams struct {
    Value wasmlib.ScImmutableInt // some optional integer parameter
}

func viewMyViewThunk(ctx *wasmlib.ScViewContext) {
    p := ctx.Params()
    params := &ViewMyViewParams {
        Value: p.GetInt(ParamValue),
    }
    viewMyView(ctx, params)
}
