// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
//////// DO NOT CHANGE THIS FILE! ////////
// Change the json schema instead

package aaa

import "github.com/iotaledger/wasp/packages/vm/wasmlib"

type Donation struct {
	Amount    int64             
	Donator   *wasmlib.ScAgentId
	Error     string            
	Feedback  string            
	Timestamp int64             
}

func NewDonationFromBytes(bytes []byte) *Donation {
	decode := wasmlib.NewBytesDecoder(bytes)
	data := &Donation{}
	data.Amount = decode.Int()
	data.Donator = decode.AgentId()
	data.Error = decode.String()
	data.Feedback = decode.String()
	data.Timestamp = decode.Int()
	return data
}

func (o *Donation) Bytes() []byte {
	return wasmlib.NewBytesEncoder().
		Int(o.Amount).
		AgentId(o.Donator).
		String(o.Error).
		String(o.Feedback).
		Int(o.Timestamp).
		Data()
}
